const GYM_KEEPER_MEDIA_HOST = '47-1594.s.cdn13.com';
const GYM_KEEPER_MEDIA_PREFIX = '/img/gifs/180/';
const MAX_EXERCISE_MEDIA_BYTES = 8 * 1024 * 1024;
const BIRD_DOG_REFERENCE_KEY = '12411305-Bird-Dog-male_Back_180.gif';
const BIRD_DOG_GYMVISUAL_PREVIEW = 'https://gymvisual.com/img/p/2/0/8/2/4/20824.gif';
const IMPORT_REPOSITORY = 'buropotok/mezfit';
const DATASET_SOURCE = 'github_exercises_dataset';
interface ExerciseMediaSourceRow { reference_source:string|null; reference_key:string|null; reference_media_url:string|null }
export function exerciseMediaPublicUrl(source:string|null,key:string|null):string|null { if(!source||!key||!['gym_keeper_apk',DATASET_SOURCE].includes(source)) return null; return `/api/exercise-media/gym_keeper_apk/${encodeURIComponent(key)}` }
export function exerciseMediaR2Key(source:string,key:string):string { return `exercise-media/${source.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}/${key}` }
export function isApprovedGymKeeperMediaUrl(value:string):boolean { try { const u=new URL(value); return u.protocol==='https:'&&u.hostname===GYM_KEEPER_MEDIA_HOST&&u.pathname.startsWith(GYM_KEEPER_MEDIA_PREFIX)&&u.pathname.toLowerCase().endsWith('.gif') } catch { return false } }
function mediaHeaders(type:string,etag?:string){const h=new Headers({'content-type':type,'cache-control':'public, max-age=31536000, immutable','x-content-type-options':'nosniff'});if(etag)h.set('etag',etag);return h}
function notFound(){return new Response(null,{status:404,headers:{'cache-control':'no-store'}})}
function validReferenceKey(key:string){return Boolean(key)&&key.length<=220&&!key.includes('/')&&key.toLowerCase().endsWith('.gif')}
async function isAuthorizedGithubImport(request:Request){if(request.headers.get('x-github-repository')!==IMPORT_REPOSITORY)return false;const authorization=request.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))return false;const response=await fetch(`https://api.github.com/repos/${IMPORT_REPOSITORY}/actions/runs?per_page=1`,{headers:{authorization,accept:'application/vnd.github+json','user-agent':'MezfitExerciseMediaImporter/1.0','x-github-api-version':'2022-11-28'}});return response.ok}
function category(v:string){v=v.toLowerCase();if(v==='chest')return'chest';if(v==='back')return'back';if(v==='shoulders')return'shoulders';if(v==='upper arms'||v==='lower arms')return'arms';if(v==='upper legs'||v==='lower legs')return'legs';if(v==='waist')return'core';if(v==='cardio')return'cardio';return'other'}
function equipmentCode(v:string){v=v.toLowerCase();if(v==='body weight'||v==='assisted')return'bodyweight';if(v.includes('barbell'))return'barbell';if(v.includes('dumbbell'))return'dumbbell_single';if(v.includes('cable'))return'cable';if(v.includes('smith')||v.includes('lever')||v.includes('sled'))return'machine';return'other'}
async function importDataset(request:Request,db:D1Database,bucket:R2Bucket,key:string,meta:any){if(!meta?.id||!/^\d{4}$/.test(String(meta.id))||!meta.name||!meta.gif_url)return new Response('invalid dataset metadata',{status:400});const mediaKey=String(meta.gif_url).split('/').pop()||'';if(mediaKey!==key)return new Response('media key mismatch',{status:400});const bytes=await request.arrayBuffer();if(bytes.byteLength<6||bytes.byteLength>MAX_EXERCISE_MEDIA_BYTES)return new Response(null,{status:400});const sig=new TextDecoder('ascii').decode(bytes.slice(0,6));if(sig!=='GIF87a'&&sig!=='GIF89a')return new Response(null,{status:415});const description=typeof meta.instructions?.ru==='string'&&meta.instructions.ru?meta.instructions.ru:(typeof meta.instructions?.en==='string'?meta.instructions.en:null);const bodyPart=String(meta.body_part||meta.category||'');const equipment=String(meta.equipment||'');const tracking=bodyPart.toLowerCase()==='cardio'?'time_distance':'weight_reps';const old=await db.prepare('SELECT id FROM exercise_definition WHERE reference_source=? AND reference_key=? LIMIT 1').bind(DATASET_SOURCE,key).first<{id:number}>();const metadata=JSON.stringify(meta);if(old){await db.prepare('UPDATE exercise_definition SET name=?,description=?,tracking_type=?,primary_muscle=?,equipment=?,category_code=?,equipment_code=?,reference_media_url=?,reference_order=?,source_metadata_json=?,is_archived=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(meta.name),description,tracking,String(meta.target||meta.muscle_group||bodyPart),equipment,category(bodyPart),equipmentCode(equipment),String(meta.gif_url),Number(meta.id),metadata,old.id).run()}else{await db.prepare("INSERT INTO exercise_definition(scope,name,description,tracking_type,primary_muscle,equipment,category_code,equipment_code,reference_source,reference_key,reference_media_url,reference_order,source_metadata_json) VALUES('global',?,?,?,?,?,?,?,?,?,?,?,?)").bind(String(meta.name),description,tracking,String(meta.target||meta.muscle_group||bodyPart),equipment,category(bodyPart),equipmentCode(equipment),DATASET_SOURCE,key,String(meta.gif_url),Number(meta.id),metadata).run()}await bucket.put(exerciseMediaR2Key(DATASET_SOURCE,key),bytes,{httpMetadata:{contentType:'image/gif',cacheControl:'public, max-age=31536000, immutable'},customMetadata:{source:DATASET_SOURCE,datasetId:String(meta.id),referenceKey:key}});return new Response(JSON.stringify({ok:true,id:String(meta.id),referenceKey:key}),{status:201,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function handleGithubImport(request:Request,db:D1Database,bucket:R2Bucket,key:string){if(!(await isAuthorizedGithubImport(request)))return new Response(null,{status:403});if(!validReferenceKey(key))return notFound();const raw=request.headers.get('x-exercise-metadata');if(raw){let meta:any;try{meta=JSON.parse(decodeURIComponent(raw))}catch{return new Response('invalid metadata',{status:400})}return importDataset(request,db,bucket,key,meta)}const source=await db.prepare("SELECT reference_source,reference_key,reference_media_url FROM exercise_definition WHERE reference_source='gym_keeper_apk' AND reference_key=? AND is_archived=0 LIMIT 1").bind(key).first<ExerciseMediaSourceRow>();if(!source?.reference_source||!source.reference_key)return notFound();const bytes=await request.arrayBuffer();if(bytes.byteLength<6||bytes.byteLength>MAX_EXERCISE_MEDIA_BYTES)return new Response(null,{status:400});const signature=new TextDecoder('ascii').decode(bytes.slice(0,6));if(signature!=='GIF87a'&&signature!=='GIF89a')return new Response(null,{status:415});await bucket.put(exerciseMediaR2Key(source.reference_source,source.reference_key),bytes,{httpMetadata:{contentType:'image/gif',cacheControl:'public, max-age=31536000, immutable'},customMetadata:{source:'github_exercises_dataset',referenceKey:source.reference_key}});return new Response(JSON.stringify({ok:true,referenceKey:source.reference_key,bytes:bytes.byteLength}),{status:201,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
export async function handleExerciseMediaRoute(request:Request,db:D1Database,bucket:R2Bucket,key:string):Promise<Response>{if(request.method==='POST')return handleGithubImport(request,db,bucket,key);if(request.method!=='GET'&&request.method!=='HEAD')return new Response(null,{status:405,headers:{allow:'GET, HEAD, POST'}});if(!validReferenceKey(key))return notFound();const source=await db.prepare('SELECT reference_source,reference_key,reference_media_url FROM exercise_definition WHERE reference_key=? AND is_archived=0 ORDER BY CASE reference_source WHEN ? THEN 0 WHEN ? THEN 1 ELSE 2 END LIMIT 1').bind(key,DATASET_SOURCE,'gym_keeper_apk').first<ExerciseMediaSourceRow>();if(!source?.reference_source||!source.reference_key)return notFound();const cached=await bucket.get(exerciseMediaR2Key(source.reference_source,source.reference_key));if(cached)return new Response(request.method==='HEAD'?null:cached.body,{status:200,headers:mediaHeaders(cached.httpMetadata?.contentType||'image/gif',cached.httpEtag)});if(source.reference_source!== 'gym_keeper_apk'||!source.reference_media_url||!isApprovedGymKeeperMediaUrl(source.reference_media_url))return notFound();const upstreamUrl=source.reference_key===BIRD_DOG_REFERENCE_KEY?BIRD_DOG_GYMVISUAL_PREVIEW:source.reference_media_url;const upstream=await fetch(upstreamUrl,{redirect:'follow',headers:{accept:'image/gif,image/*;q=0.8,*/*;q=0.1','user-agent':'MezfitExerciseMedia/1.0'}});if(!upstream.ok)return notFound();const bytes=await upstream.arrayBuffer();if(bytes.byteLength<6||bytes.byteLength>MAX_EXERCISE_MEDIA_BYTES)return notFound();const signature=new TextDecoder('ascii').decode(bytes.slice(0,6));if(signature!=='GIF87a'&&signature!=='GIF89a')return notFound();await bucket.put(exerciseMediaR2Key(source.reference_source,source.reference_key),bytes,{httpMetadata:{contentType:'image/gif',cacheControl:'public, max-age=31536000, immutable'},customMetadata:{source:source.reference_key===BIRD_DOG_REFERENCE_KEY?'gymvisual_watermarked_preview':'gym_keeper_apk',sourceUrl:upstreamUrl,referenceKey:source.reference_key}});return new Response(request.method==='HEAD'?null:bytes,{status:200,headers:mediaHeaders('image/gif')})}
