import { describe, expect, it } from 'vitest';
import { archiveExerciseForCoach, canCoachMutateExercise, listExercisesForCoach } from './exercises';
interface CapturedQuery { sql:string; args:unknown[] }
class FakeDb { rows:unknown[]=[]; firstRow:unknown=null; queries:CapturedQuery[]=[]; runCount=0; prepare(sql:string){const query={sql,args:[]} as CapturedQuery;this.queries.push(query);return{bind:(...args:unknown[])=>{query.args=args;return{all:async<T>()=>({results:this.rows as T[]}),first:async<T>()=>this.firstRow as T|null,run:async()=>{this.runCount++;return{}}}},all:async<T>()=>({results:this.rows as T[]}),first:async<T>()=>this.firstRow as T|null,run:async()=>{this.runCount++;return{}}}}}
describe('global exercise catalogue',()=>{
 it('allows mutation only for the owning coach definition',()=>{expect(canCoachMutateExercise('global',null,7)).toBe(false);expect(canCoachMutateExercise('client',7,7)).toBe(false);expect(canCoachMutateExercise('coach',8,7)).toBe(false);expect(canCoachMutateExercise('coach',7,7)).toBe(true)});
 it('queries GLOBAL plus own COACH definitions without truncating the bundled catalogue and searches the English alias in Unicode-aware application code',async()=>{const db=new FakeDb();db.rows=[{id:1,scope:'global',owner_coach_user_id:null,name:'Жим штанги лёжа',name_en:'Barbell Bench Press',description:null,tracking_type:'weight_reps',category_code:'chest',equipment_code:'barbell',reference_source:'github_exercises_dataset',reference_key:'0001',reference_media_url:null,reference_order:3,is_favourite:1},{id:2,scope:'coach',owner_coach_user_id:7,name:'Мой вариант жима',name_en:null,description:'Custom',tracking_type:'weight_reps',category_code:'chest',equipment_code:'barbell',reference_source:null,reference_key:null,reference_media_url:null,reference_order:null,is_favourite:0}];const result=await listExercisesForCoach(db as unknown as D1Database,7,{search:'bench',categoryCode:'chest',trackingType:'weight_reps',favouritesOnly:true,sort:'reference'});const sql=db.queries[0].sql.replace(/\s+/g,' ');expect(sql).toMatch(/e\.scope\s*=\s*'global' OR \(e\.scope\s*=\s*'coach' AND e\.owner_coach_user_id\s*=\s*\?\)/);expect(sql).not.toContain("e.scope = 'client'");expect(sql).toContain('e.name_en');expect(sql).not.toContain('lower(e.name) LIKE');expect(sql).toMatch(/e\.category_code\s*=\s*\?/);expect(sql).toMatch(/e\.tracking_type\s*=\s*\?/);expect(sql).toContain('f.exercise_definition_id IS NOT NULL');expect(sql).not.toMatch(/LIMIT\s+500/i);expect(db.queries[0].args).toEqual([7,7,'chest','chest','weight_reps','weight_reps',1,'reference','reference']);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({id:1,name:'Жим штанги лёжа',is_favourite:true,can_edit:false})});
 it('matches lowercase Cyrillic search against capitalized Russian bundled names',async()=>{const db=new FakeDb();db.rows=[{id:1,scope:'global',owner_coach_user_id:null,name:'Жим штанги лёжа',name_en:'Barbell Bench Press',description:null,tracking_type:'weight_reps',category_code:'chest',equipment_code:'barbell',reference_source:'github_exercises_dataset',reference_key:'0001',reference_media_url:null,reference_order:3,is_favourite:0},{id:2,scope:'global',owner_coach_user_id:null,name:'Тяга верхнего блока',name_en:'Lat Pulldown',description:null,tracking_type:'weight_reps',category_code:'back',equipment_code:'cable',reference_source:'github_exercises_dataset',reference_key:'0002',reference_media_url:null,reference_order:4,is_favourite:0}];const result=await listExercisesForCoach(db as unknown as D1Database,7,{search:'жим',categoryCode:'',trackingType:'',favouritesOnly:false,sort:'alphabetical'});expect(result).toHaveLength(1);expect(result[0].name).toBe('Жим штанги лёжа')});
 it('refuses to archive a bundled global definition',async()=>{const db=new FakeDb();db.firstRow={id:9,scope:'global',owner_coach_user_id:null};const archived=await archiveExerciseForCoach(db as unknown as D1Database,7,9);expect(archived).toBe(false);expect(db.runCount).toBe(0)});
});
