const MAX_EXERCISE_MEDIA_BYTES = 8 * 1024 * 1024;
const DATASET_SOURCE = 'github_exercises_dataset';
const EXPECTED_DATASET_SIZE = 1324;
const OIDC_ISSUER = 'https://token.actions.githubusercontent.com';
const OIDC_AUDIENCE = 'mezfit-exercise-import';
const IMPORT_REPOSITORY = 'buropotok/mezfit';
const IMPORT_WORKFLOW = 'import-exercise-media.yml';
interface ExerciseMediaSourceRow { reference_source:string|null; reference_key:string|null; reference_media_url:string|null }
export function exerciseMediaPublicUrl(source:string|null,key:string|null):string|null { if(source!==DATASET_SOURCE||!key)return null; return `/api/exercise-media/gym_keeper_apk/${encodeURIComponent(key)}` }
export function exerciseMediaR2Key(source:string,key:string):string { return `exercise-media/${source.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}/${key}.gif` }
function mediaHeaders(type:string,etag?:string){const h=new Headers({'content-type':type,'cache-control':'public, max-age=31536000, immutable','x-content-type-options':'nosniff'});if(etag)h.set('etag',etag);return h}
function notFound(){return new Response(null,{status:404,headers:{'cache-control':'no-store'}})}
function validDatasetId(key:string){return /^\d{4}$/.test(key)}
function b64url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const padded=normalized+'='.repeat((4-normalized.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0))}
async function isAuthorizedGithubImport(request:Request){try{const authorization=request.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))return false;const jwt=authorization.slice(7);const parts=jwt.split('.');if(parts.length!==3)return false;const header=JSON.parse(new TextDecoder().decode(b64url(parts[0]))) as {alg?:string;kid?:string};const claims=JSON.parse(new TextDecoder().decode(b64url(parts[1]))) as Record<string,unknown>;if(header.alg!=='RS256'||!header.kid)return false;if(claims.iss!==OIDC_ISSUER||claims.aud!==OIDC_AUDIENCE||claims.repository!==IMPORT_REPOSITORY||claims.ref!=='refs/heads/main')return false;const workflowRef=String(claims.workflow_ref||'');if(!workflowRef.startsWith(`${IMPORT_REPOSITORY}/.github/workflows/${IMPORT_WORKFLOW}@`))return false;const now=Math.floor(Date.now()/1000);if(typeof claims.exp!=='number'||claims.exp<now||typeof claims.nbf==='number'&&claims.nbf>now+30)return false;const jwksResponse=await fetch(`${OIDC_ISSUER}/.well-known/jwks`);if(!jwksResponse.ok)return false;const jwks=await jwksResponse.json() as {keys?:JsonWebKey[]};const jwk=jwks.keys?.find(k=>(k as JsonWebKey&{kid?:string}).kid===header.kid);if(!jwk)return false;const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const signed=new TextEncoder().encode(`${parts[0]}.${parts[1]}`);return crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,b64url(parts[2]),signed)}catch{return false}}
function category(v:string){v=v.toLowerCase();if(v==='chest')return'chest';if(v==='back')return'back';if(v==='shoulders')return'shoulders';if(v==='upper arms'||v==='lower arms')return'arms';if(v==='upper legs'||v==='lower legs')return'legs';if(v==='waist')return'core';if(v==='cardio')return'cardio';return'other'}
function equipmentCode(v:string){v=v.toLowerCase();if(v==='body weight'||v==='assisted')return'bodyweight';if(v.includes('barbell'))return'barbell';if(v.includes('dumbbell'))return'dumbbell_single';if(v.includes('cable'))return'cable';if(v.includes('smith')||v.includes('lever')||v.includes('sled'))return'machine';return'other'}
async function stageDataset(request:Request,db:D1Database,bucket:R2Bucket,datasetId:string,meta:any){if(!meta?.id||String(meta.id)!==datasetId||!validDatasetId(datasetId)||!meta.name||!meta.gif_url)return new Response('invalid dataset metadata',{status:400});const bytes=await request.arrayBuffer();if(bytes.byteLength<6||bytes.byteLength>MAX_EXERCISE_MEDIA_BYTES)return new Response(null,{status:400});const sig=new TextDecoder('ascii').decode(bytes.slice(0,6));if(sig!=='GIF87a'&&sig!=='GIF89a')return new Response(null,{status:415});const description=typeof meta.instructions?.ru==='string'&&meta.instructions.ru?meta.instructions.ru:(typeof meta.instructions?.en==='string'?meta.instructions.en:null);const bodyPart=String(meta.body_part||meta.category||'');const equipment=String(meta.equipment||'');const tracking=bodyPart.toLowerCase()==='cardio'?'time_distance':'weight_reps';const mediaKey=String(meta.gif_url).split('/').pop()||'';await db.prepare('INSERT INTO exercise_dataset_stage(dataset_id,name,description,tracking_type,primary_muscle,equipment,category_code,equipment_code,media_key,reference_media_url,reference_order,source_metadata_json,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(dataset_id) DO UPDATE SET name=excluded.name,description=excluded.description,tracking_type=excluded.tracking_type,primary_muscle=excluded.primary_muscle,equipment=excluded.equipment,category_code=excluded.category_code,equipment_code=excluded.equipment_code,media_key=excluded.media_key,reference_media_url=excluded.reference_media_url,reference_order=excluded.reference_order,source_metadata_json=excluded.source_metadata_json,imported_at=CURRENT_TIMESTAMP').bind(datasetId,String(meta.name),description,tracking,String(meta.target||meta.muscle_group||bodyPart),equipment,category(bodyPart),equipmentCode(equipment),mediaKey,String(meta.gif_url),Number(datasetId),JSON.stringify(meta)).run();await bucket.put(exerciseMediaR2Key(DATASET_SOURCE,datasetId),bytes,{httpMetadata:{contentType:'image/gif',cacheControl:'public, max-age=31536000, immutable'},customMetadata:{source:DATASET_SOURCE,datasetId,upstreamMediaKey:mediaKey}});return new Response(JSON.stringify({ok:true,id:datasetId}),{status:201,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function resetStage(db:D1Database){await db.prepare('DELETE FROM exercise_dataset_stage').run();return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}})}
async function finalizeDataset(db:D1Database){const count=await db.prepare('SELECT COUNT(*) AS count FROM exercise_dataset_stage').first<{count:number}>();if(Number(count?.count)!==EXPECTED_DATASET_SIZE)return new Response(`staging incomplete: ${count?.count||0}/${EXPECTED_DATASET_SIZE}`,{status:409});const statements=[];const rows=await db.prepare('SELECT * FROM exercise_dataset_stage ORDER BY dataset_id').all<any>();if(rows.results.length!==EXPECTED_DATASET_SIZE)return new Response(`staging incomplete: ${rows.results.length}/${EXPECTED_DATASET_SIZE}`,{status:409});for(const row of rows.results){statements.push(db.prepare("INSERT INTO exercise_definition(scope,name,description,tracking_type,primary_muscle,equipment,category_code,equipment_code,reference_source,reference_key,reference_media_url,reference_order,source_metadata_json,is_archived,updated_at) VALUES('global',?,?,?,?,?,?,?,?,?,?,?,?,0,CURRENT_TIMESTAMP) ON CONFLICT(reference_source,reference_key) DO UPDATE SET name=excluded.name,description=excluded.description,tracking_type=excluded.tracking_type,primary_muscle=excluded.primary_muscle,equipment=excluded.equipment,category_code=excluded.category_code,equipment_code=excluded.equipment_code,reference_media_url=excluded.reference_media_url,reference_order=excluded.reference_order,source_metadata_json=excluded.source_metadata_json,is_archived=0,updated_at=CURRENT_TIMESTAMP").bind(row.name,row.description,row.tracking_type,row.primary_muscle,row.equipment,row.category_code,row.equipment_code,DATASET_SOURCE,row.dataset_id,row.reference_media_url,row.reference_order,row.source_metadata_json))}statements.push(db.prepare("UPDATE exercise_definition SET is_archived=1,updated_at=CURRENT_TIMESTAMP WHERE scope='global' AND (COALESCE(reference_source,'')<>? OR reference_key NOT IN (SELECT dataset_id FROM exercise_dataset_stage))").bind(DATASET_SOURCE));await db.batch(statements);return new Response(JSON.stringify({ok:true,activated:EXPECTED_DATASET_SIZE}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}})}
async function handleGithubImport(request:Request,db:D1Database,bucket:R2Bucket,key:string){if(!(await isAuthorizedGithubImport(request)))return new Response(null,{status:403});if(key==='__reset__')return resetStage(db);if(key==='__finalize__')return finalizeDataset(db);if(!validDatasetId(key))return notFound();const raw=request.headers.get('x-exercise-metadata');if(!raw)return new Response('dataset metadata required',{status:400});let meta:any;try{meta=JSON.parse(decodeURIComponent(raw))}catch{return new Response('invalid metadata',{status:400})}return stageDataset(request,db,bucket,key,meta)}
export async function handleExerciseMediaRoute(request:Request,db:D1Database,bucket:R2Bucket,key:string):Promise<Response>{if(request.method==='POST')return handleGithubImport(request,db,bucket,key);if(request.method!=='GET'&&request.method!=='HEAD')return new Response(null,{status:405,headers:{allow:'GET, HEAD, POST'}});if(!validDatasetId(key))return notFound();const source=await db.prepare('SELECT reference_source,reference_key,reference_media_url FROM exercise_definition WHERE reference_source=? AND reference_key=? AND is_archived=0 LIMIT 1').bind(DATASET_SOURCE,key).first<ExerciseMediaSourceRow>();if(!source?.reference_key)return notFound();const cached=await bucket.get(exerciseMediaR2Key(DATASET_SOURCE,source.reference_key));if(!cached)return notFound();return new Response(request.method==='HEAD'?null:cached.body,{status:200,headers:mediaHeaders(cached.httpMetadata?.contentType||'image/gif',cached.httpEtag)})}
