import { useState } from 'react';
import { Avatar, Button, Divider, Dropdown, FloatingActionButton, IconButton, List, ListItem, Menu, MenuDivider, MenuItem, Modal, SearchInput, SortableList, Surface, Tabs, TabsContent, TabsList, TabsTrigger, Text, type DropdownOption, type SortableListItem } from './index';
import { ComponentTypographySettings, TypographyRoleAdmin, defaultTypographyValues, type TypographyAssignments, type TypographySlot } from './TypographyAdmin';
import { roleClass, TypographySpecimen } from './TypographySpecimen';
import './catalog.css';

const initialExercises: SortableListItem[] = [
  { id: 'bench', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🏋</span>} title="Жим лёжа · гантели" subtitle="4 подхода · Грудь" trailing="⋮" /> },
  { id: 'row', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">💪</span>} title="Тяга гантели" subtitle="4 подхода · Спина" trailing="⋮" /> },
  { id: 'squat', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🦵</span>} title="Приседания" subtitle="4 подхода · Ноги" trailing="⋮" /> },
];
const dropdownOptions: DropdownOption[] = [
  { value: 'strength', label: 'Силовая' }, { value: 'hypertrophy', label: 'Гипертрофия' }, { value: 'endurance', label: 'Выносливость' }, { value: 'mobility', label: 'Мобильность' },
  { value: 'recovery', label: 'Восстановление' }, { value: 'technique', label: 'Техника' }, { value: 'cardio', label: 'Кардио' }, { value: 'general', label: 'Общая подготовка' },
];
const buttonSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи', defaultRole: 'body' }];
const searchSlots: TypographySlot[] = [{ id: 'text', label: 'Текст / placeholder', defaultRole: 'body' }];
const avatarSlots: TypographySlot[] = [{ id: 'initials', label: 'Инициалы', defaultRole: 'footnote' }];
const menuSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи пунктов', defaultRole: 'body' }];
const tabSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи', defaultRole: 'body' }, { id: 'content', label: 'Содержимое', defaultRole: 'body' }];
const dropdownSlots: TypographySlot[] = [{ id: 'trigger', label: 'Выбранное значение', defaultRole: 'body' }, { id: 'title', label: 'Заголовок списка', defaultRole: 'headline' }, { id: 'options', label: 'Варианты', defaultRole: 'body' }, { id: 'buttons', label: 'Кнопки', defaultRole: 'body' }];
const listSlots: TypographySlot[] = [{ id: 'primary', label: 'Основная надпись', defaultRole: 'body' }, { id: 'secondary', label: 'Вспомогательная', defaultRole: 'footnote' }, { id: 'trailing', label: 'Правая подпись', defaultRole: 'footnote' }];
const modalSlots: TypographySlot[] = [{ id: 'modal-title', label: 'Заголовок', defaultRole: 'headline' }, { id: 'modal-body', label: 'Основной текст', defaultRole: 'body' }, { id: 'modal-buttons', label: 'Кнопки', defaultRole: 'body' }];
type ModalDemo = 'default' | 'info' | 'confirm' | 'destructive' | null;

export function UiKitPage() {
  const [typography, setTypography] = useState(defaultTypographyValues);
  const [modalTypography, setModalTypography] = useState<TypographyAssignments>({ 'modal-title': 'headline', 'modal-body': 'body', 'modal-buttons': 'body' });
  const [modalDemo, setModalDemo] = useState<ModalDemo>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [exercises, setExercises] = useState(initialExercises);
  const [singleValue, setSingleValue] = useState<string | null>('strength');
  const [multiValue, setMultiValue] = useState<string[]>(['strength', 'mobility']);
  const closeModal = () => setModalDemo(null);
  const modalClassName = `ui-kit-modal-demo ${roleClass('modal-title', modalTypography['modal-title'])} ${roleClass('modal-body', modalTypography['modal-body'])} ${roleClass('modal-buttons', modalTypography['modal-buttons'])}`;
  const roleCss = Object.entries(typography).map(([role, value]) => `.ui-kit-page, .ui-kit-modal-demo { --ui-kit-role-${role}-size:${value.size}px; --ui-kit-role-${role}-line:${value.lineHeight}px; --ui-kit-role-${role}-weight:${value.weight}; }`).join('\n');
  return (
    <main className="ui-kit-page">
      <style>{roleCss}</style>
      <header className="ui-kit-header"><Text variant="caption" tone="muted">Mezfit internal</Text><h1>UI Kit</h1><Text tone="muted">Foundation primitives and Telegram-derived interaction components.</Text></header>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Typography</Text><Text variant="caption" tone="muted">SF Pro on Apple devices · Golos Text on other platforms. Сначала настройте роли здесь, затем назначайте их реальным компонентам ниже.</Text><Divider /><div className="ui-kit-stack"><div><Text variant="footnote" tone="muted">Large title · Main screen title</Text><Text variant="large-title">Программа тренировок · 24/28</Text></div><div><Text variant="footnote" tone="muted">Title · Large content / section heading</Text><Text variant="title">Сегодня · 20/24</Text></div><div><Text variant="footnote" tone="muted">Headline · Modal / important heading</Text><Text variant="headline">Жим лёжа · 17/22</Text></div><div><Text variant="footnote" tone="muted">Body · Main text / inputs / controls</Text><Text>4 подхода · 8–10 повторений · 15/20</Text></div><div><Text variant="footnote" tone="muted">Footnote · Metadata / field labels</Text><Text variant="footnote" tone="muted">Последняя тренировка вчера · 13/18</Text></div><div><Text variant="footnote" tone="muted">Caption · Small supporting text</Text><Text variant="caption" tone="muted">ОБНОВЛЕНО 12:45 · MEZFIT · 12/16</Text></div></div><Divider /><Text variant="headline">Typography admin</Text><TypographyRoleAdmin values={typography} onChange={setTypography} /></Surface>

      <Surface as="section" className="ui-kit-section"><Text variant="title">Buttons</Text><Divider /><TypographySpecimen kind="buttons" slots={buttonSlots} values={typography}><div className="ui-kit-row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="danger">Danger</Button><Button disabled>Disabled</Button></div></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Search</Text><Divider /><TypographySpecimen kind="search" slots={searchSlots} values={typography}><SearchInput aria-label="Поиск" placeholder="Поиск" value={search} onChange={(event) => setSearch(event.currentTarget.value)} onClear={() => setSearch('')} /></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Icon button & avatar</Text><Divider /><TypographySpecimen kind="avatar" slots={avatarSlots} values={typography}><div className="ui-kit-row"><IconButton label="Add item"><span aria-hidden="true">＋</span></IconButton><IconButton label="Disabled action" disabled><span aria-hidden="true">⋯</span></IconButton><Avatar name="Mezfit User" /></div></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Menu</Text><Divider /><TypographySpecimen kind="menu" slots={menuSlots} values={typography}><Menu isOpen={menuOpen} onOpenChange={setMenuOpen} label="Example menu" trigger={<button type="button" className="ui-icon-button" aria-label="Open menu"><span aria-hidden="true">⋮</span></button>}><MenuItem leading={<span>ⓘ</span>}>Информация</MenuItem><MenuItem active leading={<span>★</span>}>Избранное</MenuItem><MenuDivider /><MenuItem leading={<span>✎</span>}>Редактировать</MenuItem></Menu></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Tabs</Text><Divider /><TypographySpecimen kind="tabs" slots={tabSlots} values={typography}><Tabs defaultValue="overview"><TabsList aria-label="Client sections"><TabsTrigger value="overview">Обзор</TabsTrigger><TabsTrigger value="program">Программа</TabsTrigger><TabsTrigger value="exercises">Упражнения</TabsTrigger><TabsTrigger value="calendar">Календарь</TabsTrigger></TabsList><TabsContent value="overview"><Text>Обзор клиента</Text></TabsContent><TabsContent value="program"><Text>Программа клиента</Text></TabsContent><TabsContent value="exercises"><Text>Упражнения клиента</Text></TabsContent><TabsContent value="calendar"><Text>Календарь клиента</Text></TabsContent></Tabs></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Dropdown</Text><Text variant="caption" tone="muted">Telegram-style выбор: синее значение открывает модалку со списком.</Text><Divider /><TypographySpecimen kind="dropdown" slots={dropdownSlots} values={typography}><div className="ui-kit-stack"><div><Text tone="muted">Single: </Text><Dropdown mode="single" title="Цель тренировки" options={dropdownOptions} value={singleValue} onChange={setSingleValue} /></div><div><Text tone="muted">Multi: </Text><Dropdown mode="multi" title="Направления" options={dropdownOptions} value={multiValue} onChange={setMultiValue} /></div></div></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section" style={{ position: 'relative', minHeight: '19rem' }}><Text variant="title">Telegram lists</Text><Divider /><TypographySpecimen kind="list" slots={listSlots} values={typography}><List><ListItem leading={<Avatar name="Andrei Sokolov" />} title="Andrei Sokolov" subtitle="@sokolag" /><ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🏋</span>} title="Жим лёжа · гантели" subtitle="Вес × повторы · Грудь · Гантели x2" trailing="База" /><ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">💪</span>} title="Грудь" trailing="29" /></List><FloatingActionButton label="Добавить клиента" onClick={() => setModalDemo('default')}><span aria-hidden="true">＋</span></FloatingActionButton></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Telegram list · text only</Text><Text variant="caption" tone="muted">Без leading-картинки: высота строки определяется текстом и вертикальными отступами.</Text><Divider /><TypographySpecimen kind="list" slots={listSlots} values={typography}><List><ListItem title="Первый вариант" /><ListItem title="Второй вариант" /><ListItem title="Третий вариант" /><ListItem title="Четвёртый вариант" /></List></TypographySpecimen></Surface>
      <Surface as="section" className="ui-kit-section"><Text variant="title">Sortable Telegram list</Text><Text variant="caption" tone="muted">Удерживайте строку и перетащите её. Интерактивные элементы можно исключить через data-no-dnd.</Text><Divider /><TypographySpecimen kind="sortable-list" slots={listSlots} values={typography}><SortableList items={exercises} onReorder={setExercises} /></TypographySpecimen></Surface>
      <Surface as="section" elevated className="ui-kit-section"><Text variant="title">Modal</Text><Text variant="caption" tone="muted">Content modal и Telegram Web A alert/confirm варианты на общей Radix-основе.</Text><Divider /><div className="ui-kit-row"><Button onClick={() => setModalDemo('default')}>Content</Button><Button variant="secondary" onClick={() => setModalDemo('info')}>Info</Button><Button variant="secondary" onClick={() => setModalDemo('confirm')}>Confirm</Button><Button variant="danger" onClick={() => setModalDemo('destructive')}>Delete</Button></div><ComponentTypographySettings slots={modalSlots} assignments={modalTypography} onChange={setModalTypography} /></Surface>
      <Modal className={modalClassName} isOpen={modalDemo === 'default'} title="Пригласить клиента" onClose={closeModal}><Text>Здесь будет ссылка-приглашение и действие копирования.</Text></Modal>
      <Modal className={modalClassName} isOpen={modalDemo === 'info'} variant="alert" title="Готово" onClose={closeModal} actions={[{ id: 'ok', label: 'OK', onClick: closeModal }]}><Text>Изменения сохранены.</Text></Modal>
      <Modal className={modalClassName} isOpen={modalDemo === 'confirm'} variant="alert" title="Завершить тренировку?" onClose={closeModal} actions={[{ id: 'confirm', label: 'Завершить', onClick: closeModal }, { id: 'cancel', label: 'Отмена', onClick: closeModal }]}><Text>После завершения результаты будут сохранены.</Text></Modal>
      <Modal className={modalClassName} isOpen={modalDemo === 'destructive'} variant="alert" title="Удалить тренировку?" onClose={closeModal} actions={[{ id: 'delete', label: 'Удалить', tone: 'danger', onClick: closeModal }, { id: 'cancel', label: 'Отмена', onClick: closeModal }]}><Text>Это действие нельзя отменить.</Text></Modal>
    </main>
  );
}
