import { useRef, useState } from 'react';
import { List as KonstaList, ListItem as KonstaListItem, Radio as KonstaRadio } from 'konsta/react';
import { Avatar, Badge, BottomSheet, Button, DatePicker, Divider, Dropdown, FloatingActionButton, GlassSurface, IconButton, IdentityAction, List, ListItem, Menu, MenuDivider, MenuItem, MezfitDialog, MezfitDialogButton, MezfitPopover, MezfitSearchbar, MezfitSidePanel, MezfitSlider, Modal, NumPicker, SearchInput, WeightRepsPicker, SortableList, Surface, Tabs, TabsContent, TabsList, TabsTrigger, Text, TimePicker, type BadgeColor, type DropdownOption, type GlassPresetName, type LocalDate, type LocalTime, type SortableListItem, type TimePickerLensMode } from './index';
import { ComponentTypographySettings, TypographyRoleAdmin, defaultTypographyValues, type TypographyAssignments, type TypographySlot } from './TypographyAdmin';
import { typographyValueStyle, TypographySpecimen } from './TypographySpecimen';
import { FormControlsCatalog } from './FormControlsCatalog';
import { GlassBackgroundLab } from './GlassBackgroundLab';
import { NestedBadgesCatalog } from './NestedBadgesCatalog';
import dotsVerticalIconUrl from './icons/dots-vertical.svg';
import { LiquidPopoverCatalog } from './LiquidPopoverCatalog';
import './catalog.css';

const initialExercises: SortableListItem[] = [
  { id: 'bench', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🏋</span>} title="Жим лёжа · гантели" subtitle="4 подхода · Грудь" trailing="⋮" /> },
  { id: 'row', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">💪</span>} title="Тяга гантели" subtitle="4 подхода · Спина" trailing="⋮" /> },
  { id: 'squat', content: <ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🦵</span>} title="Приседания" subtitle="4 подхода · Ноги" trailing="⋮" /> },
];
const dropdownOptions: DropdownOption[] = [
  { value: 'strength', label: 'Силовая' }, { value: 'hypertrophy', label: 'Гипертрофия' }, { value: 'endurance', label: 'Выносливость' }, { value: 'mobility', label: 'Мобильность' },
  { value: 'recovery', label: 'Восстановление' }, { value: 'technique', label: 'Техника' }, { value: 'cardio', label: 'Кардио' }, { value: 'general', label: 'Общая подготовка' },
];
const badgeColors: BadgeColor[] = ['green', 'yellow', 'blue', 'red', 'orange', 'purple', 'cyan', 'gray'];
const sliderSizes = ['big', 'medium', 'small'] as const;
const glassPresets: readonly { name: GlassPresetName; label: string; description: string }[] = [
  { name: 'modalTuned', label: 'Modal Tuned', description: 'Default · approved prototype' },
  { name: 'modal', label: 'Modal', description: 'Soft modal variant from prototype' },
  { name: 'lens', label: 'Lens', description: 'Low blur · optical edge' },
  { name: 'clear', label: 'Clear', description: 'Light tint · restrained refraction' },
  { name: 'frosted', label: 'Frosted', description: 'High blur · soft material' },
  { name: 'blue', label: 'Blue', description: 'Tinted · saturated glass' },
  { name: 'smoked', label: 'Smoked', description: 'Dark tint · stronger shadow' },
  { name: 'liquidConvex', label: 'Liquid Convex', description: 'Borderless · scaled convex edge and paired bezel' },
];

const buttonSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи', defaultRole: 'body', selector: '.ui-button', weightOverride: 500 }];
const searchSlots: TypographySlot[] = [{ id: 'text', label: 'Текст / placeholder', defaultRole: 'body', selector: '.ui-search-input__field' }];
const avatarSlots: TypographySlot[] = [{ id: 'initials', label: 'Инициалы', defaultRole: 'footnote', selector: '.ui-avatar--fallback', weightOverride: 600 }];
const menuSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи пунктов', defaultRole: 'body', selector: '.ui-menu-item__label', weightOverride: 500 }];
const tabSlots: TypographySlot[] = [{ id: 'labels', label: 'Подписи', defaultRole: 'body', selector: '.ui-tabs__trigger, .ui-tabs__indicator-tab', weightOverride: 500 }];
const dropdownSlots: TypographySlot[] = [
  { id: 'trigger', label: 'Выбранное значение', defaultRole: 'body', selector: '.ui-dropdown__trigger', weightOverride: 500 },
  { id: 'title', label: 'Заголовок списка', defaultRole: 'headline', selector: '.ui-dropdown__modal .ui-modal__title' },
  { id: 'options', label: 'Варианты', defaultRole: 'body', selector: '.ui-dropdown__options .ui-list-item__title', weightOverride: 600 },
  { id: 'buttons', label: 'Кнопки', defaultRole: 'body', selector: '.ui-dropdown__confirm', weightOverride: 500 },
];
const listSlots: TypographySlot[] = [
  { id: 'primary', label: 'Основная надпись', defaultRole: 'body', selector: '.ui-list-item__title', weightOverride: 600 },
  { id: 'secondary', label: 'Вспомогательная', defaultRole: 'footnote', selector: '.ui-list-item__subtitle' },
  { id: 'trailing', label: 'Правая подпись', defaultRole: 'footnote', selector: '.ui-list-item__trailing' },
];
type MezfitDialogDemo = 'content' | 'info' | 'confirm' | 'list' | 'delete' | null;
type ModalDemo = 'default' | 'info' | 'confirm' | 'destructive' | null;
type BottomSheetDemo = 'modal' | 'surface' | 'inset' | null;
type SidePanelSide = 'left' | 'right';

export function UiKitPage() {
  const [typography, setTypography] = useState(defaultTypographyValues);
  const [menuTypography, setMenuTypography] = useState<TypographyAssignments>({ labels: 'body' });
  const [dropdownTypography, setDropdownTypography] = useState<TypographyAssignments>({ trigger: 'body', title: 'headline', options: 'body', buttons: 'body' });
  const [fabAction, setFabAction] = useState('');
  const [modalDemo, setModalDemo] = useState<ModalDemo>(null);
  const [bottomSheetDemo, setBottomSheetDemo] = useState<BottomSheetDemo>(null);
  const [sidePanelSide, setSidePanelSide] = useState<SidePanelSide>('left');
  const [sidePanelOpen, setSidePanelOpen] = useState(false);
  const [dialogDemo, setDialogDemo] = useState<MezfitDialogDemo>(null);
  const [dialogListValue, setDialogListValue] = useState('strength');
  const [popoverOpen, setPopoverOpen] = useState(false);
  const popoverTargetRef = useRef<HTMLSpanElement | null>(null);
  const [datePickerOpen, setDatePickerOpen] = useState(false);
  const [datePickerValue, setDatePickerValue] = useState<LocalDate>('2026-09-25');
  const timePickerTargetRef = useRef<HTMLSpanElement | null>(null);
  const [timePickerOpen, setTimePickerOpen] = useState(false);
  const [timePickerValue, setTimePickerValue] = useState<LocalTime>('08:30');
  const [timePickerLensMode, setTimePickerLensMode] = useState<TimePickerLensMode>('auto');
  const numPickerTargetRef = useRef<HTMLSpanElement | null>(null);
  const [numPickerOpen, setNumPickerOpen] = useState(false);
  const [numPickerValue, setNumPickerValue] = useState(123);
  const weightRepsPickerTargetRef = useRef<HTMLSpanElement | null>(null);
  const [weightRepsPickerOpen, setWeightRepsPickerOpen] = useState(false);
  const [weightRepsPickerValue, setWeightRepsPickerValue] = useState({ reps: 8, weightKg: 77.5 });
  const [menuOpen, setMenuOpen] = useState(false);
  const [listActionMenuOpen, setListActionMenuOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [sliderValues, setSliderValues] = useState({ big: 0, medium: 0, small: 0 });
  const [exercises, setExercises] = useState(initialExercises);
  const [plainExercises, setPlainExercises] = useState(initialExercises);
  const [singleValue, setSingleValue] = useState<string | null>('strength');
  const [multiValue, setMultiValue] = useState<string[]>(['strength', 'mobility']);
  const closeDialog = () => setDialogDemo(null);
  const closeModal = () => setModalDemo(null);
  const styleRule = (selector: string, role: keyof typeof typography, weightOverride?: number) => { const value = typography[role]; return `${selector}{font-family:var(--ui-font-family);font-size:${value.size}px;line-height:${value.lineHeight}px;font-weight:${weightOverride ?? value.weight};}`; };
  const portalCss = [
    styleRule('.ui-kit-menu-demo .ui-menu-item__label', menuTypography.labels, 500),
    styleRule('.ui-kit-dropdown-demo .ui-modal__title', dropdownTypography.title),
    styleRule('.ui-kit-dropdown-demo .ui-dropdown__options .ui-list-item__title', dropdownTypography.options, 600),
    styleRule('.ui-kit-dropdown-demo .ui-dropdown__confirm', dropdownTypography.buttons, 500),
  ].join('\n');

  return <main className="ui-kit-page">
    <style>{portalCss}</style>
    <header className="ui-kit-header"><Text variant="caption" tone="muted">Mezfit internal</Text><h1>UI Kit</h1><Text tone="muted">Foundation primitives and Telegram-derived interaction components.</Text></header>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Typography</Text><Text variant="caption" tone="muted">Zen Maru Gothic · shared Mezfit font family. Сначала настройте роли здесь, затем назначайте их реальным компонентам ниже.</Text><Divider /><div className="ui-kit-stack"><div><Text variant="footnote" tone="muted">Large title · Main screen title</Text><Text variant="large-title">Программа тренировок · 24/28</Text></div><div><Text variant="footnote" tone="muted">Title · Large content / section heading</Text><Text variant="title">Сегодня · 20/24</Text></div><div><Text variant="footnote" tone="muted">Headline · Modal / important heading</Text><Text variant="headline">Жим лёжа · 17/22</Text></div><div><Text variant="footnote" tone="muted">Body · Main text / inputs / controls</Text><Text>4 подхода · 8–10 повторений · 15/20</Text></div><div><Text variant="footnote" tone="muted">Footnote · Metadata / field labels</Text><Text variant="footnote" tone="muted">Последняя тренировка вчера · 13/18</Text></div><div><Text variant="footnote" tone="muted">Caption · Small supporting text</Text><Text variant="caption" tone="muted">ОБНОВЛЕНО 12:45 · MEZFIT · 12/16</Text></div></div><Divider /><Text variant="headline">Typography admin</Text><TypographyRoleAdmin values={typography} onChange={setTypography} /></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Surface</Text><Text variant="caption" tone="muted">Container primitive. Border is enabled by default and can be disabled with border=false.</Text><Divider /><div className="ui-kit-stack"><Surface style={{ padding: 'var(--ui-space-3)' }}><Text>border=true · default</Text></Surface><Surface border={false} style={{ padding: 'var(--ui-space-3)' }}><Text>border=false</Text></Surface><Surface elevated style={{ padding: 'var(--ui-space-3)' }}><Text>elevated</Text></Surface></div></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Glass material</Text><Text variant="caption" tone="muted">Parametric Mezfit glass. Modal Tuned is the default material; all material properties remain publicly overridable through GlassSurface.</Text><Divider /><div className="ui-kit-glass-material-grid">{glassPresets.map(({ name, label, description }) => <div key={name} className="ui-kit-glass-material-stage"><div className="ui-kit-glass-material-stage__backdrop" aria-hidden="true"><span className="ui-kit-glass-material-stage__spot ui-kit-glass-material-stage__spot--circle" /><span className="ui-kit-glass-material-stage__spot ui-kit-glass-material-stage__spot--rect" /><span className="ui-kit-glass-material-stage__text">MEZFIT GLASS OPTICS</span></div><GlassSurface preset={name} className="ui-kit-glass-material-card" contentClassName="ui-kit-glass-material-card__content"><Text variant="headline">{label}</Text><Text variant="caption" tone="muted">{description}</Text></GlassSurface></div>)}</div></Surface>
    <GlassBackgroundLab />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Buttons</Text><Divider /><TypographySpecimen kind="buttons" slots={buttonSlots} values={typography}><div className="ui-kit-row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="danger">Danger</Button><Button disabled>Disabled</Button></div></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Badges</Text><Text variant="caption" tone="muted">Universal color variants; feature code owns the label meaning. Typography: Body.</Text><Divider /><div className="ui-kit-row">{badgeColors.map((color) => <Badge key={color} color={color}>{color}</Badge>)}</div></Surface>
    <NestedBadgesCatalog values={typography} />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Search</Text><Divider /><TypographySpecimen kind="search" slots={searchSlots} values={typography}><SearchInput aria-label="Поиск" placeholder="Поиск" value={search} onChange={(event) => setSearch(event.currentTarget.value)} onClear={() => setSearch('')} /></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Mezfit Searchbar</Text><Text variant="caption" tone="muted">Konsta Searchbar 5.4.0 mechanics with the Konsta Glass substrate replaced by GlassSurface. glassPreset / glassOptics accept the application glass settings.</Text><Divider /><MezfitSearchbar placeholder="Поиск" value={search} onChange={(event) => setSearch(event.currentTarget.value)} onClear={() => setSearch('')} disableButton glassPreset="frosted" glassOptics={false} /></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Mezfit Slider</Text><Text variant="caption" tone="muted">Konsta Range 5.4.0 mechanics with the Kube-derived liquid-glass lens encapsulated inside the UI Kit adapter. Big = prototype, Medium = 0.75×, Small = 0.5×.</Text><Divider /><div className="ui-kit-stack">{sliderSizes.map((size) => <div key={size} className="ui-kit-stack"><Text variant="footnote" tone="muted">{size} · Value {sliderValues[size]}</Text><MezfitSlider size={size} start={0} end={100} ariaLabel={`Mezfit Slider ${size}`} onValueChange={(value) => setSliderValues((current) => ({ ...current, [size]: value }))} /></div>)}</div></Surface>
    <FormControlsCatalog />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Icon button & avatar</Text><Divider /><TypographySpecimen kind="avatar" slots={avatarSlots} values={typography}><div className="ui-kit-row"><IconButton label="Add item"><span aria-hidden="true">＋</span></IconButton><IconButton label="Disabled action" disabled><span aria-hidden="true">⋯</span></IconButton><Avatar name="Mezfit User" /></div></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Identity action</Text><Text variant="caption" tone="muted">Mezfit navbar action on GlassSurface. Labeled: avatar/icon + title. Single: 44×44. Double: one capsule with two independent icon actions.</Text><Divider /><div className="ui-kit-glass-stage"><div className="ui-kit-glass-stage__backdrop"><Text variant="footnote" tone="muted">Контент под glass-поверхностью</Text><Text>Профиль клиента</Text></div><div className="ui-kit-glass-stage__foreground"><div className="ui-kit-row"><IdentityAction avatar={{ name: 'Andrei Sokolov' }} title="Andrei Sokolov" onClick={() => {}} /><IdentityAction avatar={{ name: 'Andrei Sokolov' }} title="Andrei Sokolov" variant="single" onClick={() => {}} /><IdentityAction variant="double" actions={[{ icon: 'dots-vertical', label: 'Меню', onClick: () => {} }, { icon: 'calendar', label: 'Календарь', onClick: () => {} }]} /><IdentityAction avatar={{ name: 'Disabled User' }} title="Disabled User" disabled /></div></div></div></Surface>
    <LiquidPopoverCatalog />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Menu</Text><Divider /><Menu isOpen={menuOpen} onOpenChange={setMenuOpen} label="Example menu" className="ui-kit-menu-demo" trigger={<button type="button" className="ui-icon-button" aria-label="Open menu"><span aria-hidden="true">⋮</span></button>}><MenuItem leading={<span>ⓘ</span>}>Информация</MenuItem><MenuItem active leading={<span>★</span>}>Избранное</MenuItem><MenuDivider /><MenuItem leading={<span>✎</span>}>Редактировать</MenuItem></Menu><ComponentTypographySettings slots={menuSlots} assignments={menuTypography} values={typography} onChange={setMenuTypography} /></Surface>
    {/* Temporarily unmounted to isolate catalog overflow affecting DatePicker. */}
    {false && <Surface as="section" className="ui-kit-section"><Text variant="title">Tabs</Text><Divider /><TypographySpecimen kind="tabs" slots={tabSlots} values={typography}><Tabs defaultValue="overview"><TabsList aria-label="Client sections"><TabsTrigger value="overview">Обзор</TabsTrigger><TabsTrigger value="program">Программа</TabsTrigger><TabsTrigger value="exercises">Упражнения</TabsTrigger><TabsTrigger value="calendar">Календарь</TabsTrigger></TabsList><TabsContent value="overview"><Text>Обзор клиента</Text></TabsContent><TabsContent value="program"><Text>Программа клиента</Text></TabsContent><TabsContent value="exercises"><Text>Упражнения клиента</Text></TabsContent><TabsContent value="calendar"><Text>Календарь клиента</Text></TabsContent></Tabs></TypographySpecimen></Surface>}
    <Surface as="section" className="ui-kit-section"><Text variant="title">Dropdown</Text><Text variant="caption" tone="muted">Telegram-style выбор: синее значение открывает модалку со списком.</Text><Divider /><div className="ui-kit-stack"><div><Text tone="muted">Single: </Text><Dropdown mode="single" title="Цель тренировки" options={dropdownOptions} value={singleValue} onChange={setSingleValue} triggerProps={{ style: typographyValueStyle(dropdownTypography.trigger, typography, 500) }} modalClassName="ui-kit-dropdown-demo" /></div><div><Text tone="muted">Multi: </Text><Dropdown mode="multi" title="Направления" options={dropdownOptions} value={multiValue} onChange={setMultiValue} triggerProps={{ style: typographyValueStyle(dropdownTypography.trigger, typography, 500) }} modalClassName="ui-kit-dropdown-demo" /></div></div><ComponentTypographySettings slots={dropdownSlots} assignments={dropdownTypography} values={typography} onChange={setDropdownTypography} /></Surface>
    <Surface as="section" className="ui-kit-section" style={{ position: 'relative', minHeight: '12rem' }}><Text variant="title">FAB · Metaball</Text><Divider /><Text variant="body">Горизонтальное разделение · 44 CSS px · Headline</Text><Text variant="footnote" role="status">{fabAction}</Text><FloatingActionButton label="Добавить в программу" mode="metaball" icon="plus" actions={[{ label: 'День', onClick: () => setFabAction('Добавить день в выбранную фазу') }, { label: 'Фаза', onClick: () => setFabAction('Добавить фазу') }]} /></Surface>
    <Surface as="section" className="ui-kit-section" style={{ position: 'relative', minHeight: '19rem' }}><Text variant="title">Telegram lists</Text><Divider /><TypographySpecimen kind="list" slots={listSlots} values={typography}><List><ListItem leading={<Avatar name="Andrei Sokolov" />} title="Andrei Sokolov" subtitle="@sokolag" /><ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">🏋</span>} title="Жим лёжа · гантели" subtitle="Вес × повторы · Грудь · Гантели x2" trailing="База" /><ListItem leadingShape="square" leading={<span style={{ display: 'grid', placeItems: 'center', background: 'var(--ui-color-surface-raised)' }} aria-hidden="true">💪</span>} title="Грудь" trailing="29" /><ListItem title="Интерактивная строка + action" trailing={<span aria-hidden="true">●</span>} trailingAction={<Menu isOpen={listActionMenuOpen} onOpenChange={setListActionMenuOpen} align="end" label="Действия строки" trigger={<IconButton label="Действия строки"><img src={dotsVerticalIconUrl} alt="" aria-hidden="true" width={24} height={24} /></IconButton>}><MenuItem>Информация</MenuItem></Menu>} onClick={() => {}} /></List><FloatingActionButton label="Добавить клиента" icon="user-plus" onClick={() => setModalDemo('default')} /><FloatingActionButton label="Подтвердить" placement="left">ОК</FloatingActionButton></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Telegram list · text only</Text><Text variant="caption" tone="muted">Без leading-картинки: высота строки определяется текстом и вертикальными отступами.</Text><Divider /><TypographySpecimen kind="list" slots={listSlots} values={typography}><List><ListItem title="Первый вариант" /><ListItem title="Второй вариант" /><ListItem title="Третий вариант" /><ListItem title="Четвёртый вариант" /></List></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Sortable Telegram list</Text><Text variant="caption" tone="muted">Удерживайте строку и перетащите её. Разделители включены по умолчанию и отключаются через showSeparators.</Text><Divider /><TypographySpecimen kind="sortable-list" slots={listSlots} values={typography}><div className="ui-kit-stack"><div><Text variant="footnote" tone="muted">С разделителями · default</Text><SortableList items={exercises} onReorder={setExercises} /></div><div><Text variant="footnote" tone="muted">Без разделителей · showSeparators=false</Text><SortableList items={plainExercises} onReorder={setPlainExercises} showSeparators={false} /></div></div></TypographySpecimen></Surface>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Date picker</Text><Text variant="caption" tone="muted">Единый date-only picker: Konsta floating Panel, год в glass-кнопке и Konsta Popover с прокручиваемой сеткой годов.</Text><Divider /><div className="ui-kit-stack"><Text>Выбрано: {datePickerValue}</Text><div className="ui-kit-row"><Button onClick={() => setDatePickerOpen(true)}>Открыть календарь</Button></div></div></Surface>
    <DatePicker opened={datePickerOpen} value={datePickerValue} onChange={setDatePickerValue} onClose={() => setDatePickerOpen(false)} />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Time picker</Text><Text variant="caption" tone="muted">По умолчанию используется auto: на iOS линза увеличивает цифры через scale без SVG displacement, на остальных платформах сохраняется displacement-map.</Text><Divider /><div className="ui-kit-stack"><Text>Выбрано: {timePickerValue}</Text><Text variant="caption" tone="muted">Режим: {timePickerLensMode}</Text><span ref={timePickerTargetRef} className="ui-kit-row"><Button onClick={() => { setTimePickerLensMode('auto'); setTimePickerOpen(true); }}>Выбрать время</Button><Button variant="secondary" onClick={() => { setTimePickerLensMode('ios'); setTimePickerOpen(true); }}>iOS mode</Button></span></div></Surface>
    <TimePicker opened={timePickerOpen} lensMode={timePickerLensMode} target={timePickerTargetRef.current} value={timePickerValue} onChange={setTimePickerValue} onClose={() => setTimePickerOpen(false)} />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Num picker</Text><Text variant="caption" tone="muted">Число 0–399 на той же линзе и scroll-ribbon механике: слева пусто/1/2/3 сотни, справа 00–99.</Text><Divider /><div className="ui-kit-stack"><Text>Выбрано: {numPickerValue}</Text><span ref={numPickerTargetRef} style={{ display: 'inline-flex' }}><Button onClick={() => setNumPickerOpen(true)}>Выбрать число</Button></span></div></Surface>
    <NumPicker opened={numPickerOpen} target={numPickerTargetRef.current} value={numPickerValue} onChange={setNumPickerValue} onClose={() => setNumPickerOpen(false)} />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Вес + повторения</Text><Text variant="caption" tone="muted">Единая форма для подхода: повторения занимают левую половину, вес — правую половину с отдельными колёсами килограммов и долей 00 / 25 / 5.</Text><Divider /><div className="ui-kit-stack"><Text>Повторения: {weightRepsPickerValue.reps} · Вес: {weightRepsPickerValue.weightKg} кг</Text><span ref={weightRepsPickerTargetRef} style={{ display: 'inline-flex' }}><Button onClick={() => setWeightRepsPickerOpen(true)}>Выбрать повторения и вес</Button></span></div></Surface>
    <WeightRepsPicker opened={weightRepsPickerOpen} target={weightRepsPickerTargetRef.current} value={weightRepsPickerValue} onChange={setWeightRepsPickerValue} onClose={() => setWeightRepsPickerOpen(false)} />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Mezfit Side Panel</Text><Text variant="caption" tone="muted">Konsta Panel / Side Panel mechanics are preserved. In the iOS floating variant only the Konsta Glass material is replaced by the UI Kit GlassSurface.</Text><Divider /><div className="ui-kit-row"><Button onClick={() => { setSidePanelSide('left'); setSidePanelOpen(true); }}>Открыть слева</Button><Button variant="secondary" onClick={() => { setSidePanelSide('right'); setSidePanelOpen(true); }}>Открыть справа</Button></div></Surface>
    <MezfitSidePanel side={sidePanelSide} opened={sidePanelOpen} floating onBackdropClick={() => setSidePanelOpen(false)} role="dialog" aria-modal="true" aria-label="Mezfit Side Panel"><div style={{ display: 'grid', gap: 'var(--ui-space-3)', padding: 'var(--ui-space-4)' }}><Text variant="headline">Mezfit Side Panel</Text><Text tone="muted">Штатная механика Konsta Side Panel с материалом GlassSurface из UI Kit.</Text><Button onClick={() => setSidePanelOpen(false)}>Закрыть</Button></div></MezfitSidePanel>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Mezfit Dialog</Text><Text variant="caption" tone="muted">Konsta Dialog mechanics, layout and transitions are preserved; Glass is replaced by GlassSurface. The catalog covers the four canonical Konsta compositions plus the Mezfit destructive Delete scenario.</Text><Divider /><div className="ui-kit-row"><Button onClick={() => setDialogDemo('content')}>Content</Button><Button variant="secondary" onClick={() => setDialogDemo('info')}>Info</Button><Button variant="secondary" onClick={() => setDialogDemo('confirm')}>Confirm</Button><Button variant="secondary" onClick={() => setDialogDemo('list')}>List</Button><Button variant="danger" onClick={() => setDialogDemo('delete')}>Delete</Button></div></Surface>
    <MezfitDialog opened={dialogDemo === 'content'} onBackdropClick={closeDialog} title="Пригласить клиента" content="Здесь будет ссылка-приглашение и действие копирования." buttons={<><MezfitDialogButton onClick={closeDialog}>Закрыть</MezfitDialogButton><MezfitDialogButton strong onClick={closeDialog}>Копировать</MezfitDialogButton></>} role="dialog" aria-modal="true" aria-label="Content dialog" />
    <MezfitDialog opened={dialogDemo === 'info'} onBackdropClick={closeDialog} title="Готово" content="Изменения сохранены." buttons={<MezfitDialogButton strong onClick={closeDialog}>OK</MezfitDialogButton>} role="alertdialog" aria-modal="true" aria-label="Info dialog" />
    <MezfitDialog opened={dialogDemo === 'confirm'} onBackdropClick={closeDialog} title="Завершить тренировку?" content="После завершения результаты будут сохранены." buttons={<><MezfitDialogButton onClick={closeDialog}>Отмена</MezfitDialogButton><MezfitDialogButton strong onClick={closeDialog}>Завершить</MezfitDialogButton></>} role="alertdialog" aria-modal="true" aria-label="Confirm dialog" />
    <MezfitDialog opened={dialogDemo === 'list'} onBackdropClick={closeDialog} title="Цель тренировки" content={<KonstaList nested className="-mx-4"><KonstaListItem label title="Силовая" after={<KonstaRadio component="div" value="strength" checked={dialogListValue === 'strength'} onChange={() => setDialogListValue('strength')} />} /><KonstaListItem label title="Гипертрофия" after={<KonstaRadio component="div" value="hypertrophy" checked={dialogListValue === 'hypertrophy'} onChange={() => setDialogListValue('hypertrophy')} />} /><KonstaListItem label title="Мобильность" after={<KonstaRadio component="div" value="mobility" checked={dialogListValue === 'mobility'} onChange={() => setDialogListValue('mobility')} />} /></KonstaList>} buttons={<MezfitDialogButton strong onClick={closeDialog}>Подтвердить</MezfitDialogButton>} role="dialog" aria-modal="true" aria-label="List dialog" />
    <MezfitDialog opened={dialogDemo === 'delete'} onBackdropClick={closeDialog} title="Удалить тренировку?" content="Это действие нельзя отменить." buttons={<><MezfitDialogButton onClick={closeDialog}>Отмена</MezfitDialogButton><MezfitDialogButton strong tone="danger" onClick={closeDialog}>Удалить</MezfitDialogButton></>} role="alertdialog" aria-modal="true" aria-label="Delete dialog" />
    <Surface as="section" className="ui-kit-section"><Text variant="title">Mezfit Popover</Text><Text variant="caption" tone="muted">Konsta Popover mechanics are preserved. Only the inner iOS Konsta Glass renderer is replaced by the UI Kit GlassSurface.</Text><Divider /><span ref={popoverTargetRef} style={{ display: 'inline-flex' }}><Button onClick={() => setPopoverOpen(true)}>Открыть Popover</Button></span></Surface>
    <MezfitPopover opened={popoverOpen} target={popoverTargetRef.current ?? undefined} backdrop onBackdropClick={() => setPopoverOpen(false)} role="dialog" aria-modal="true" aria-label="Mezfit Popover"><div style={{ display: 'grid', gap: 'var(--ui-space-3)', padding: 'var(--ui-space-4)' }}><Text variant="headline">Mezfit Popover</Text><Text tone="muted">Штатная механика Konsta Popover с материалом GlassSurface из UI Kit.</Text><Button onClick={() => setPopoverOpen(false)}>Закрыть</Button></div></MezfitPopover>
    <Surface as="section" className="ui-kit-section"><Text variant="title">Bottom sheet</Text><Text variant="caption" tone="muted">Большая overlay-поверхность снизу. По умолчанию modalColor=true использует --ui-color-modal; modalColor=false оставляет обычный surface. inset=true добавляет UI Kit-owned отступы от краёв и полное скругление.</Text><Divider /><div className="ui-kit-row"><Button onClick={() => setBottomSheetDemo('modal')}>modalColor=true</Button><Button variant="secondary" onClick={() => setBottomSheetDemo('surface')}>modalColor=false</Button><Button variant="secondary" onClick={() => setBottomSheetDemo('inset')}>inset=true</Button></div></Surface>
    <BottomSheet isOpen={bottomSheetDemo !== null} title="Упражнения" modalColor={bottomSheetDemo !== 'surface'} inset={bottomSheetDemo === 'inset'} onClose={() => setBottomSheetDemo(null)}><div style={{ padding: '0 1.5rem 1.5rem' }}><Text tone="muted">Пример полноразмерного рабочего пространства внутри тренировки.</Text><List divider="inset"><ListItem title="Грудь" trailing="12" /><ListItem title="Спина" trailing="15" /><ListItem title="Ноги" trailing="18" /></List></div></BottomSheet>
    <Surface as="section" elevated className="ui-kit-section"><Text variant="title">Modal</Text><Text variant="caption" tone="muted">Компактные modal/confirm используют Konsta Dialog с iOS glass и штатными DialogButton. Длинные рабочие формы пока остаются legacy.</Text><Divider /><div className="ui-kit-row"><Button onClick={() => setModalDemo('default')}>Content</Button><Button variant="secondary" onClick={() => setModalDemo('info')}>Info</Button><Button variant="secondary" onClick={() => setModalDemo('confirm')}>Confirm</Button><Button variant="danger" onClick={() => setModalDemo('destructive')}>Delete</Button></div></Surface>
    <Modal isOpen={modalDemo === 'default'} presentation="dialog" title="Пригласить клиента" onClose={closeModal} className="ui-kit-modal-demo" actions={[{ id: 'cancel', label: 'Закрыть', onClick: closeModal }, { id: 'copy', label: 'Копировать', tone: 'primary', onClick: closeModal }]}><Text>Здесь будет ссылка-приглашение и действие копирования.</Text></Modal>
    <Modal isOpen={modalDemo === 'info'} variant="confirm" title="Готово" onClose={closeModal} className="ui-kit-modal-demo" actions={[{ id: 'ok', label: 'OK', tone: 'primary', onClick: closeModal }]}><Text>Изменения сохранены.</Text></Modal>
    <Modal isOpen={modalDemo === 'confirm'} variant="confirm" title="Завершить тренировку?" onClose={closeModal} className="ui-kit-modal-demo" actions={[{ id: 'cancel', label: 'Отмена', onClick: closeModal }, { id: 'confirm', label: 'Завершить', tone: 'primary', onClick: closeModal }]}><Text>После завершения результаты будут сохранены.</Text></Modal>
    <Modal isOpen={modalDemo === 'destructive'} variant="confirm" title="Удалить тренировку?" onClose={closeModal} className="ui-kit-modal-demo" actions={[{ id: 'cancel', label: 'Отмена', onClick: closeModal }, { id: 'delete', label: 'Удалить', tone: 'danger', onClick: closeModal }]}><Text>Это действие нельзя отменить.</Text></Modal>
  </main>;
}
