PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', '3 4 Sit up', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '00011305-3-4-Sit-up_Waist_180.gif', 1),
  ('global', 'Alternate Heel Touchers', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '00061305-Alternate-Heel-Touchers_waist-FIX_180.gif', 2),
  ('global', 'Barbell Bench Press', 'weight_reps', 'chest', 'barbell', 'gym_keeper_apk', '00251305-Barbell-Bench-Press_Chest_180.gif', 3),
  ('global', 'Barbell Bench Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00261305-Barbell-Bench-Squat_Hips-FIX_180.gif', 4),
  ('global', 'Barbell Bent Over Row', 'weight_reps', 'back', 'barbell', 'gym_keeper_apk', '00271305-Barbell-Bent-Over-Row_Back-FIX_180.gif', 5),
  ('global', 'Barbell Close Grip Bench Press', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00301305-Barbell-Close-Grip-Bench-Press_Upper-Arms_180.gif', 6),
  ('global', 'Barbell Curl', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00311305-Barbell-Curl_Upper-Arms_180.gif', 7),
  ('global', 'Barbell Deadlift', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00321305-Barbell-Deadlift_Hips-FIX_180.gif', 8),
  ('global', 'Barbell Decline Bench Press', 'weight_reps', 'chest', 'barbell', 'gym_keeper_apk', '00331305-Barbell-Decline-Bench-Press_Chest_180.gif', 9),
  ('global', 'Barbell Front Raise', 'weight_reps', 'shoulders', 'barbell', 'gym_keeper_apk', '00411305-Barbell-Front-Raise_Shoulders_180.gif', 10),
  ('global', 'Barbell Front Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00421305-Barbell-Front-Squat_Hips-FIX_180.gif', 11),
  ('global', 'Barbell Full Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00431305-Barbell-Full-Squat_Thighs_180.gif', 12),
  ('global', 'Barbell Hack Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00461305-Barbell-Hack-Squat_Hips_180.gif', 13),
  ('global', 'Barbell Incline Bench Press', 'weight_reps', 'chest', 'barbell', 'gym_keeper_apk', '00471305-Barbell-Incline-Bench-Press_Chest_180.gif', 14),
  ('global', 'Barbell Incline Row', 'weight_reps', 'back', 'barbell', 'gym_keeper_apk', '00491305-Barbell-Incline-Row_Back-FIX_180.gif', 15),
  ('global', 'Barbell Lunge', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00541305-Barbell-Lunge_Thighs_180.gif', 16),
  ('global', 'Barbell Lying Triceps Extension', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00611305-Barbell-Lying-Triceps-Extension_Upper-Arms_180.gif', 17),
  ('global', 'Barbell Rack Pull', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00741305-Barbell-Rack-Pull_Hips-FIX_180.gif', 18),
  ('global', 'Barbell Rear Delt Row', 'weight_reps', 'shoulders', 'barbell', 'gym_keeper_apk', '00761305-Barbell-Rear-Delt-Row_shoulder-FIX_180.gif', 19),
  ('global', 'Barbell Rear Lunge', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00781305-Barbell-Rear-Lunge_Thighs_180.gif', 20),
  ('global', 'Barbell Reverse Curl', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00801305-Barbell-Reverse-Curl_Forearm_180.gif', 21),
  ('global', 'Barbell Romanian Deadlift', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00851305-Barbell-Romanian-Deadlift_Hips_180.gif', 22),
  ('global', 'Barbell Seated Calf Raise', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00881305-Barbell-Seated-Calf-Raise_Calves_180.gif', 23),
  ('global', 'Barbell Seated Close grip Concentration Curl', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00891305-Barbell-Seated-Close-grip-Concentration-Curl_Upper-Arms_180.gif', 24),
  ('global', 'Barbell Seated Overhead Press', 'weight_reps', 'shoulders', 'barbell', 'gym_keeper_apk', '00911305-Barbell-Seated-Overhead-Press_Shoulders_180.gif', 25),
  ('global', 'Barbell Seated Overhead Triceps Extension', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '00921305-Barbell-Seated-Overhead-Triceps-Extension_Upper-Arms_180.gif', 26),
  ('global', 'Barbell Shrug', 'weight_reps', 'back', 'barbell', 'gym_keeper_apk', '00951305-Barbell-Shrug_Back_180.gif', 27),
  ('global', 'Barbell Single Leg Split Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '00991305-Barbell-Single-Leg-Split-Squat_Hips-FIX_180.gif', 28),
  ('global', 'Barbell Standing Back Wrist Curl', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '01041305-Barbell-Standing-Back-Wrist-Curl_Forearms_180.gif', 29),
  ('global', 'Barbell Standing Leg Calf Raise', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '01081305-Barbell-Standing-Leg-Calf-Raise_Calf_180.gif', 30),
  ('global', 'Barbell Step up', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '01141305-Barbell-Step-up_Hips_180.gif', 31),
  ('global', 'Barbell Sumo Deadlift', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '01171305-Barbell-Sumo-Deadlift_Hips_180.gif', 32),
  ('global', 'Barbell Wide Grip Upright Row', 'weight_reps', 'shoulders', 'barbell', 'gym_keeper_apk', '01231305-Barbell-Wide-Grip-Upright-Row_Shoulders_180.gif', 33),
  ('global', 'Barbell Zercher Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '01271305-Barbell-Zercher-Squat_Hips_180.gif', 34),
  ('global', 'Battling Ropes', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '01281305-Battling-Ropes_180.gif', 35),
  ('global', 'Butt Kicks (female)', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '01461305-Butt-Kicks-(female)_Cardio-FIX_180.gif', 36),
  ('global', 'Cable Bench Press', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '01511305-Cable-Bench-Press_Chest_180.gif', 37),
  ('global', 'Cable Cross over Revers Fly', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '01541305-Cable-Cross-over-Revers-Fly_Shoulders_180.gif', 38),
  ('global', 'Cable Decline Fly', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '01581305-Cable-Decline-Fly_Chest-FIX_180.gif', 39),
  ('global', 'Cable Front Raise', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '01621305-Cable-Front-Raise_Shoulders_180.gif', 40),
  ('global', 'Cable Hammer Curl (with rope attachment) (male)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '01651305-Cable-Hammer-Curl-(with-rope-attachment)-(male)_Forearms-FIX_180.gif', 41),
  ('global', 'Cable Hip Adduction', 'weight_reps', 'legs', 'cable', 'gym_keeper_apk', '01681305-Cable-Hip-Adduction_Thighs_180.gif', 42),
  ('global', 'Cable Incline Bench Press', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '01691305-Cable-Incline-Bench-Press_Chest_180.gif', 43),
  ('global', 'Cable Incline Fly', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '01711305-Cable-Incline-Fly_Chest_180.gif', 44),
  ('global', 'Cable Kneeling Crunch', 'time_distance', 'core', 'cable', 'gym_keeper_apk', '01751305-Cable-Kneeling-Crunch_Waist-FIX_180.gif', 45),
  ('global', 'Cable Lateral Raise', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '01781305-Cable-Lateral-Raise_shoulder_180.gif', 46),
  ('global', 'Cable Lying Extension Pullover (with rope attachment)', 'weight_reps', 'other', 'cable', 'gym_keeper_apk', '01841305-Cable-Lying-Extension-Pullover-(with-rope-attachment)_180.gif', 47),
  ('global', 'Cable Lying Fly', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '01851305-Cable-Lying-Fly_Chest_180.gif', 48),
  ('global', 'Cable One Arm Bent over Row', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '01891305-Cable-One-Arm-Bent-over-Row_Back-FIX_180.gif', 49),
  ('global', 'Cable Overhead Triceps Extension (rope attachment)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '01941305-Cable-Overhead-Triceps-Extension-(rope-attachment)_Upper-Arms_180.gif', 50);
