PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', 'Cable Pull Through (with rope)', 'weight_reps', 'legs', 'cable', 'gym_keeper_apk', '01961305-Cable-Pull-Through-(with-rope)_Hip_180.gif', 51),
  ('global', 'Cable Pulldown (pro lat bar)', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '01971305-Cable-Pulldown-(pro-lat-bar)_Back_180.gif', 52),
  ('global', 'Cable Shoulder Press', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '02191305-Cable-Shoulder-Press_Shoulders_180.gif', 53),
  ('global', 'Cable Shrug', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '02201305-Cable-Shrug_Back_180.gif', 54),
  ('global', 'Cable Side Bend', 'weight_reps', 'core', 'cable', 'gym_keeper_apk', '02221305-Cable-Side-Bend_Waist-FIX_180.gif', 55),
  ('global', 'Cable Side Crunch', 'time_distance', 'core', 'cable', 'gym_keeper_apk', '02231305-Cable-Side-Crunch_Waist_180.gif', 56),
  ('global', 'Cable Standing Cross over High Reverse Fly', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '02251305-Cable-Standing-Cross-over-High-Reverse-Fly_Shoulders_180.gif', 57),
  ('global', 'Cable Standing Rear Delt Row (with rope)', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '02331305-Cable-Standing-Rear-Delt-Row-(with-rope)_shoulder_180.gif', 58),
  ('global', 'Cable Standing Shoulder External Rotation', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '02351305-Cable-Standing-Shoulder-External-Rotation_Back-FIX_180.gif', 59),
  ('global', 'Cable Triceps Pushdown (V bar attachment)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '02411305-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms_180.gif', 60),
  ('global', 'Cable Upright Row', 'weight_reps', 'shoulders', 'cable', 'gym_keeper_apk', '02461305-Cable-Upright-Row_Shoulders-FIX_180.gif', 61),
  ('global', 'Cross Body Twisting Crunch', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '02631305-Cross-Body-Twisting-Crunch_waist_180.gif', 62),
  ('global', 'Crunch (on stability ball)', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '02711305-Crunch-(on-stability-ball)_waist_180.gif', 63),
  ('global', 'Crunch Floor m', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '02741305-Crunch-Floor-m_waist_180.gif', 64),
  ('global', 'Decline Crunch', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '02771305-Decline-Crunch_waist_180.gif', 65),
  ('global', 'Decline Push Up m', 'weight_reps', 'chest', 'bodyweight', 'gym_keeper_apk', '02791305-Decline-Push-Up-m_chest_180.gif', 66),
  ('global', 'Decline Sit up', 'weight_reps', 'legs', 'bodyweight', 'gym_keeper_apk', '02821305-Decline-Sit-up_Hips-FIX_180.gif', 67),
  ('global', 'Diamond Push up', 'weight_reps', 'arms', 'bodyweight', 'gym_keeper_apk', '02831305-Diamond-Push-up_Upper-Arms_180.gif', 68),
  ('global', 'Dumbbell Alternate Biceps Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '02851305-Dumbbell-Alternate-Biceps-Curl_Upper-Arms_180.gif', 69),
  ('global', 'Dumbbell Bench Press', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '02891305-Dumbbell-Bench-Press_Chest_180.gif', 70),
  ('global', 'Dumbbell Bench Squat', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '02911305-Dumbbell-Bench-Squat_thighs_180.gif', 71),
  ('global', 'Dumbbell Bent over Row_back', 'weight_reps', 'back', 'dumbbell_pair', 'gym_keeper_apk', '02921305-Dumbbell-Bent-over-Row_back_Back_180.gif', 72),
  ('global', 'Dumbbell Bent Over Row', 'weight_reps', 'back', 'dumbbell_pair', 'gym_keeper_apk', '02931305-Dumbbell-Bent-Over-Row_Back-FIX_180.gif', 73),
  ('global', 'Dumbbell Biceps Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '02941305-Dumbbell-Biceps-Curl_Upper-Arms_180.gif', 74),
  ('global', 'Dumbbell Concentration Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '02971305-Dumbbell-Concentration-Curl_Upper-Arms_180.gif', 75),
  ('global', 'Dumbbell Decline Bench Press', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '03011305-Dumbbell-Decline-Bench-Press_Chest_180.gif', 76),
  ('global', 'Dumbbell Decline Fly', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '03021305-Dumbbell-Decline-Fly_Chest_180.gif', 77),
  ('global', 'Dumbbell Decline Shrug (VERSION 2)', 'weight_reps', 'back', 'dumbbell_pair', 'gym_keeper_apk', '03041305-Dumbbell-Decline-Shrug-(VERSION-2)_Back-FIX_180.gif', 78),
  ('global', 'Dumbbell Fly', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '03081305-Dumbbell-Fly_Chest-FIX_180.gif', 79),
  ('global', 'Dumbbell Front Raise', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '03101305-Dumbbell-Front-Raise_Shoulders_180.gif', 80),
  ('global', 'Dumbbell Hammer Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03131305-Dumbbell-Hammer-Curl_Forearm_180.gif', 81),
  ('global', 'Dumbbell Incline Bench Press', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '03141305-Dumbbell-Incline-Bench-Press_Chest_180.gif', 82),
  ('global', 'Dumbbell Incline Biceps Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03151305-Dumbbell-Incline-Biceps-Curl_Upper-Arms_180.gif', 83),
  ('global', 'Dumbbell Incline Fly', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '03191305-Dumbbell-Incline-Fly_Chest-FIX_180.gif', 84),
  ('global', 'Dumbbell Incline Row', 'weight_reps', 'back', 'dumbbell_pair', 'gym_keeper_apk', '03271305-Dumbbell-Incline-Row_Back_180.gif', 85),
  ('global', 'Dumbbell Iron Cross', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '03321305-Dumbbell-Iron-Cross_Shoulders_180.gif', 86),
  ('global', 'Dumbbell Lateral Raise', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '03341305-Dumbbell-Lateral-Raise_shoulder_180.gif', 87),
  ('global', 'Dumbbell Lunge', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '03361305-Dumbbell-Lunge_Hips_180.gif', 88),
  ('global', 'Dumbbell Lying Triceps Extension', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03511305-Dumbbell-Lying-Triceps-Extension_Upper-Arms_180.gif', 89),
  ('global', 'Dumbbell One Arm Triceps Extension (on bench)', 'weight_reps', 'arms', 'dumbbell_single', 'gym_keeper_apk', '03621305-Dumbbell-One-Arm-Triceps-Extension-(on-bench)_Upper-Arms_180.gif', 90),
  ('global', 'Dumbbell Peacher Hammer Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03701305-Dumbbell-Peacher-Hammer-Curl_Forearms_180.gif', 91),
  ('global', 'Dumbbell Preacher Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03721305-Dumbbell-Preacher-Curl_Upper-Arms_180.gif', 92),
  ('global', 'Dumbbell Prone Incline Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03741305-Dumbbell-Prone-Incline-Curl_Upper-Arms_180.gif', 93),
  ('global', 'Dumbbell Rear Lateral Raise', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '03801305-Dumbbell-Rear-Lateral-Raise_Shoulders_180.gif', 94),
  ('global', 'Dumbbell Rear Lunge', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '03811305-Dumbbell-Rear-Lunge_Thighs_180.gif', 95),
  ('global', 'Dumbbell Reverse Fly', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '03831305-Dumbbell-Reverse-Fly_Shoulders_180.gif', 96),
  ('global', 'Dumbbell Seated Bench Extension', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '03891305-Dumbbell-Seated-Bench-Extension_Upper-Arms-FIX_180.gif', 97),
  ('global', 'Dumbbell Seated Palms Up Wrist Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04011305-Dumbbell-Seated-Palms-Up-Wrist-Curl_Forearms_180.gif', 98),
  ('global', 'Dumbbell Seated Preacher Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04021305-Dumbbell-Seated-Preacher-Curl_Upper-Arms_180.gif', 99),
  ('global', 'Dumbbell Seated Revers grip Concentration Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04031305-Dumbbell-Seated-Revers-grip-Concentration-Curl_Forearms_180.gif', 100);
