PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', 'Dumbbell Seated Shoulder Press', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '04051305-Dumbbell-Seated-Shoulder-Press_Shoulders_180.gif', 101),
  ('global', 'Dumbbell Shrug', 'weight_reps', 'back', 'dumbbell_pair', 'gym_keeper_apk', '04061305-Dumbbell-Shrug_Back-FIX_180.gif', 102),
  ('global', 'Dumbbell Side Bend', 'weight_reps', 'core', 'dumbbell_pair', 'gym_keeper_apk', '04071305-Dumbbell-Side-Bend_Waist_180.gif', 103),
  ('global', 'Dumbbell Single Leg Split Squat', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '04101305-Dumbbell-Single-Leg-Split-Squat_Thighs-FIX_180.gif', 104),
  ('global', 'Dumbbell Standing Calf Raise', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '04171305-Dumbbell-Standing-Calf-Raise_Calf_180.gif', 105),
  ('global', 'Dumbbell Standing Kickback', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04201305-Dumbbell-Standing-Kickback_Upper-Arms_180.gif', 106),
  ('global', 'Dumbbell Standing Overhead Press', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '04261305-Dumbbell-Standing-Overhead-Press_shoulder_180.gif', 107),
  ('global', 'Dumbbell Standing Reverse Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04291305-Dumbbell-Standing-Reverse-Curl_Forearms_180.gif', 108),
  ('global', 'Dumbbell Step up', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '04311305-Dumbbell-Step-up_Hips_180.gif', 109),
  ('global', 'Dumbbell Straight Arm Pullover', 'weight_reps', 'chest', 'dumbbell_pair', 'gym_keeper_apk', '04331305-Dumbbell-Straight-Arm-Pullover_Chest-FIX_180.gif', 110),
  ('global', 'Dumbbell Straight Leg Deadlift', 'weight_reps', 'core', 'dumbbell_pair', 'gym_keeper_apk', '04341305-Dumbbell-Straight-Leg-Deadlift_Waist_180.gif', 111),
  ('global', 'Dumbbell Upright Row', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '04371305-Dumbbell-Upright-Row_shoulder_180.gif', 112),
  ('global', 'Dumbbell Zottman Curl', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '04391305-Dumbbell-Zottman-Curl_Upper-Arms-FIX_180.gif', 113),
  ('global', 'EZ Barbell Spider Curl', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '04541305-EZ-Barbell-Spider-Curl_Upper-Arms_180.gif', 114),
  ('global', 'Flutter Kicks', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '04591305-Flutter-Kicks_hips_180.gif', 115),
  ('global', 'Front Plank', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '04631305-Front-Plank_waist-FIX_180.gif', 116),
  ('global', 'Gorilla Chin', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '04671305-Gorilla-Chin_waist_180.gif', 117),
  ('global', 'Handstand Push Up', 'weight_reps', 'shoulders', 'bodyweight', 'gym_keeper_apk', '04711305-Handstand-Push-Up_Shoulders_180.gif', 118),
  ('global', 'Hanging Leg Raise', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '04721305-Hanging-Leg-Raise_Hips_180.gif', 119),
  ('global', 'Hanging Straight Leg Raise', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '04751305-Hanging-Straight-Leg-Raise_Hips_180.gif', 120),
  ('global', 'Hanging Straight Twisting Leg Hip Raise', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '04761305-Hanging-Straight-Twisting-Leg-Hip-Raise_waist-FIX_180.gif', 121),
  ('global', 'High Knee Skips', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '04771305-High-Knee-Skips_Cardio_180.gif', 122),
  ('global', 'Hyperextension', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '04891305-Hyperextension_Waist_180.gif', 123),
  ('global', 'Incline Push up', 'weight_reps', 'chest', 'bodyweight', 'gym_keeper_apk', '04931305-Incline-Push-up_Chest_180.gif', 124),
  ('global', 'Inverted Row', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '04991305-Inverted-Row_Back-FIX_180.gif', 125),
  ('global', 'Jackknife Sit Up', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '05071305-Jackknife-Sit-Up_waist_180.gif', 126),
  ('global', 'Jump Split', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '05121305-Jump-Split_Plyometrics_180.gif', 127),
  ('global', 'Jump Squat', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '05141305-Jump-Squat_Thighs_180.gif', 128),
  ('global', 'Jumping Jack', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '05161305-Jumping-Jack_Cardio_180.gif', 129),
  ('global', 'Kettlebell Goblet Squat', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '05341305-Kettlebell-Goblet-Squat_thighs_180.gif', 130),
  ('global', 'Kettlebell Swing', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '05491305-Kettlebell-Swing_Kettlebell_180.gif', 131),
  ('global', 'Kettlebell Thruster', 'weight_reps', 'shoulders', 'other', 'gym_keeper_apk', '05501305-Kettlebell-Thruster_Shoulders_180.gif', 132),
  ('global', 'Kettlebell Turkish Get Up (Squat style)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '05511305-Kettlebell-Turkish-Get-Up-(Squat-style)_Thighs-FIX_180.gif', 133),
  ('global', 'Kettlebell Windmill', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '05541305-Kettlebell-Windmill_waist_180.gif', 134),
  ('global', 'Lateral Box Jump', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '05641305-Lateral-Box-Jump_Plyometrics-copy_180.gif', 135),
  ('global', 'Lever Kneeling Twist', 'weight_reps', 'core', 'machine', 'gym_keeper_apk', '05831305-Lever-Kneeling-Twist_Waist_180.gif', 136),
  ('global', 'Lever Lateral Raise', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '05841305-Lever-Lateral-Raise_shoulder_180.gif', 137),
  ('global', 'Lever Leg Extension', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05851305-Lever-Leg-Extension_Thighs_180.gif', 138),
  ('global', 'Lever Lying Leg Curl', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05861305-Lever-Lying-Leg-Curl_Thighs_180.gif', 139),
  ('global', 'Lever Reverse Hyperextension (plate loaded)', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05931305-Lever-Reverse-Hyperextension-(plate-loaded)_Hips_180.gif', 140),
  ('global', 'Lever Seated Calf Raise (plate loaded)', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05941305-Lever-Seated-Calf-Raise-(plate-loaded)_Calf_180.gif', 141),
  ('global', 'Lever Seated Fly', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '05961305-Lever-Seated-Fly_Chest_180.gif', 142),
  ('global', 'Lever Seated Hip Abduction', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05971305-Lever-Seated-Hip-Abduction_Hips-FIX_180.gif', 143),
  ('global', 'Lever Seated Hip Adduction', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05981305-Lever-Seated-Hip-Adduction_Thighs_180.gif', 144),
  ('global', 'Lever Seated Leg Curl', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '05991305-Lever-Seated-Leg-Curl_Thighs-FIX_180.gif', 145),
  ('global', 'Lever Seated Reverse Fly', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '06021305-Lever-Seated-Reverse-Fly_Shoulders_180.gif', 146),
  ('global', 'Lever Standing Calf Raise', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '06051305-Lever-Standing-Calf-Raise_Calf_180.gif', 147),
  ('global', 'Lever T bar Row (plate loaded)', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '06061305-Lever-T-bar-Row-(plate-loaded)_Back_180.gif', 148),
  ('global', 'Lever Triceps Extension', 'weight_reps', 'arms', 'machine', 'gym_keeper_apk', '06071305-Lever-Triceps-Extension_Upper-Arms_180.gif', 149),
  ('global', 'Lunge', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '06121305-Lunge_Hips_180.gif', 150);
