PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', 'Mountain Climber', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '06301305-Mountain-Climber_Cardio_180.gif', 151),
  ('global', 'Oblique Crunches Floor', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '06351305-Oblique-Crunches-Floor_waist_180.gif', 152),
  ('global', 'Power Clean', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '06481305-Power-Clean_Weightlifting-FIX_180.gif', 153),
  ('global', 'Pull up', 'weight_reps', 'back', 'bodyweight', 'gym_keeper_apk', '06521305-Pull-up_Back_180.gif', 154),
  ('global', 'Push up m', 'weight_reps', 'chest', 'bodyweight', 'gym_keeper_apk', '06621305-Push-up-m_Chest-FIX_180.gif', 155),
  ('global', 'Russian Twist', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '06871305-Russian-Twist_Waist-FIX_180.gif', 156),
  ('global', 'Side Hip Abduction', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '07101305-Side-Hip-Abduction_Hips_180.gif', 157),
  ('global', 'Side Plank m', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '07151305-Side-Plank-m_Waist_180.gif', 158),
  ('global', 'Side Push up', 'weight_reps', 'arms', 'bodyweight', 'gym_keeper_apk', '07171305-Side-Push-up_Upper-Arms-FIX_180.gif', 159),
  ('global', 'Sit (wall)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '07341305-Sit-(wall)_Thighs_180.gif', 160),
  ('global', 'Sled Leg Press', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07391305-Sled-Leg-Press_Hips_180.gif', 161),
  ('global', 'Sled Hack Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07431305-Sled-Hack-Squat_Hips_180.gif', 162),
  ('global', 'Smith Back Shrug', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '07461305-Smith-Back-Shrug_Back_180.gif', 163),
  ('global', 'Smith Bench Press', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '07481305-Smith-Bench-Press_Chest-FIX_180.gif', 164),
  ('global', 'Smith Bent Knee Good morning', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07491305-Smith-Bent-Knee-Good-morning_Hips_180.gif', 165),
  ('global', 'Smith Close Grip Bench Press', 'weight_reps', 'arms', 'machine', 'gym_keeper_apk', '07511305-Smith-Close-Grip-Bench-Press_Upper-Arms_180.gif', 166),
  ('global', 'Smith Deadlift', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07521305-Smith-Deadlift_Hips-FIX_180.gif', 167),
  ('global', 'Smith Decline Bench Press', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '07531305-Smith-Decline-Bench-Press_Chest_180.gif', 168),
  ('global', 'Smith Hack Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07551305-Smith-Hack-Squat_Hips_180.gif', 169),
  ('global', 'Smith Incline Bench Press', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '07571305-Smith-Incline-Bench-Press_Chest-FIX_180.gif', 170),
  ('global', 'Smith Bent Over Row (VERSION 2)', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '07621305-Smith-Bent-Over-Row-(VERSION-2)_Back-FIX_180.gif', 171),
  ('global', 'Smith Seated Shoulder Press', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '07651305-Smith-Seated-Shoulder-Press_Shoulders_180.gif', 172),
  ('global', 'Smith Shrug', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '07671305-Smith-Shrug_Back_180.gif', 173),
  ('global', 'Smith Split Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07691305-Smith-Split-Squat_Thighs-FIX_180.gif', 174),
  ('global', 'Smith Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07701305-Smith-Squat_Hips_180.gif', 175),
  ('global', 'Smith Standing Behind Head Military Press', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '07721305-Smith-Standing-Behind-Head-Military-Press_Shoulders_180.gif', 176),
  ('global', 'Smith Standing Leg Calf Raise', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '07731305-Smith-Standing-Leg-Calf-Raise_Calves-FIX_180.gif', 177),
  ('global', 'Smith Upright Row', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '07751305-Smith-Upright-Row_shoulder_180.gif', 178),
  ('global', 'Stationary Bike Walk', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '07981305-Stationary-Bike-Walk_Cardio_180.gif', 179),
  ('global', 'Step up', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '08011305-Step-up_Hips_180.gif', 180),
  ('global', 'Triceps Dip', 'weight_reps', 'arms', 'other', 'gym_keeper_apk', '08141305-Triceps-Dip_Upper-Arms_180.gif', 181),
  ('global', 'Wheel Rollout', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '08571305-Wheel-Rollout_Waist-FIX_180.gif', 182),
  ('global', 'Cable kickback', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '08601305-Cable-kickback_Upper-arms-FIX_180.gif', 183),
  ('global', 'Cable twist (up down)', 'weight_reps', 'core', 'cable', 'gym_keeper_apk', '08621305-Cable-twist-(up-down)_Waist_180.gif', 184),
  ('global', 'Reverse plank', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '08671305-Reverse-plank_Waist-FIX_180.gif', 185),
  ('global', 'Cable Reverse Crunch', 'time_distance', 'core', 'cable', 'gym_keeper_apk', '08731305-Cable-Reverse-Crunch_Waist-FIX_180.gif', 186),
  ('global', 'Dumbbell Curtsey lunge', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '08811305-Dumbbell-Curtsey-lunge_Thighs_180.gif', 187),
  ('global', 'Lever stepper', 'time_distance', 'cardio', 'machine', 'gym_keeper_apk', '09381305-Lever-stepper_Cardio-copy_180.gif', 188),
  ('global', 'Band squat row', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '10031305-Band-squat-row_Back_180.gif', 189),
  ('global', 'Lever Pec Deck Fly', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '10301305-Lever-Pec-Deck-Fly_Chest_180.gif', 190),
  ('global', 'Lever Standing Leg Raise', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '10361305-Lever-Standing-Leg-Raise_Hips_180.gif', 191),
  ('global', 'Cable Close Grip Front Lat Pulldown', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '10471305-Cable-Close-Grip-Front-Lat-Pulldown_Back-copy_180.gif', 192),
  ('global', 'Barbell Hip Thrust', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '10601305-Barbell-Hip-Thrust_Hips_180.gif', 193),
  ('global', 'Barbell sumo squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '10631305-Barbell-sumo-squat_Thighs-AFIX_180.gif', 194),
  ('global', 'Burpee', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '11601305-Burpee_Cardio_180.gif', 195),
  ('global', 'Rowing (with rowing machine)', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '11611305-Rowing-(with-rowing-machine)_Cardio_180.gif', 196),
  ('global', 'Lying Leg Raise', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '11631305-Lying-Leg-Raise_Waist_180.gif', 197),
  ('global', 'Barbell Standing Military Press (without rack)', 'weight_reps', 'shoulders', 'barbell', 'gym_keeper_apk', '11651305-Barbell-Standing-Military-Press-(without-rack)_Shoulders_180.gif', 198),
  ('global', 'Incline Twisting Sit up (version 2)', 'weight_reps', 'core', 'bodyweight', 'gym_keeper_apk', '11901305-Incline-Twisting-Sit-up-(version-2)_Waist-FIX_180.gif', 199),
  ('global', 'Triceps Press (Head Below Bench)', 'weight_reps', 'arms', 'other', 'gym_keeper_apk', '11911305-Triceps-Press-(Head-Below-Bench)_Upper-Arms_180.gif', 200);
