PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', 'Squat m', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '11971305-Squat-m_Thighs_180.gif', 201),
  ('global', 'Sumo Deadlift High Pull_Thighs', 'weight_reps', 'shoulders', 'other', 'gym_keeper_apk', '11991305-Sumo-Deadlift-High-Pull_Thighs_Shoulders_180.gif', 202),
  ('global', 'Lever Shrug (bench press machine)', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '12211305-Lever-Shrug-(bench-press-machine)_Back_180.gif', 203),
  ('global', 'Cable Seated Row (Bent bar)', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '12381305-Cable-Seated-Row-(Bent-bar)_Back_180.gif', 204),
  ('global', 'Bird Dog male', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '12411305-Bird-Dog-male_Back_180.gif', 205),
  ('global', 'Dead Bug (version 2)', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '12431305-Dead-Bug-(version-2)_waist_180.gif', 206),
  ('global', 'Flutter Kicks (version 3)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '12441305-Flutter-Kicks-(version-3)_Hips-FIX_180.gif', 207),
  ('global', 'Wipers (straight leg)', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '12491305-Wipers-(straight-leg)_Waist_180.gif', 208),
  ('global', 'Barbell Decline Pullover', 'weight_reps', 'chest', 'barbell', 'gym_keeper_apk', '12551305-Barbell-Decline-Pullover_Chest_180.gif', 209),
  ('global', 'Cable Decline Press', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '12611305-Cable-Decline-Press_Chest_180.gif', 210),
  ('global', 'Cable Standing Up Straight Crossovers', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '12691305-Cable-Standing-Up-Straight-Crossovers_Chest_180.gif', 211),
  ('global', 'Back Extension on Exercise Ball', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '13141305-Back-Extension-on-Exercise-Ball_Back_180.gif', 212),
  ('global', 'Cable Rope Extension Incline Bench Row', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '13221305-Cable-Rope-Extension-Incline-Bench-Row_Back_180.gif', 213),
  ('global', 'Cable Wide Grip Rear Pulldown Behind Neck', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '13251305-Cable-Wide-Grip-Rear-Pulldown-Behind-Neck_Back_180.gif', 214),
  ('global', 'Chin Up', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '13261305-Chin-Up_Back_180.gif', 215),
  ('global', 'Close Grip Chin Up', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '13271305-Close-Grip-Chin-Up_Back_180.gif', 216),
  ('global', 'Lever Seated Row', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '13501305-Lever-Seated-Row_Back_180.gif', 217),
  ('global', 'Medicine Ball Overhead Slam', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '13541305-Medicine-Ball-Overhead-Slam_Back_180.gif', 218),
  ('global', 'Smith Bent Over Row', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '13591305-Smith-Bent-Over-Row_Back_180.gif', 219),
  ('global', 'Dumbbell Seated Calf Raise', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '13791305-Dumbbell-Seated-Calf-Raise_Calves_180.gif', 220),
  ('global', 'Sled Calf Press On Leg Press', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '13911305-Sled-Calf-Press-On-Leg-Press_Calves_180.gif', 221),
  ('global', 'Bench dip on floor', 'weight_reps', 'arms', 'other', 'gym_keeper_apk', '13991305-Bench-dip-on-floor_Upper-Arms_180.gif', 222),
  ('global', 'Muscle up (on vertical bar)', 'weight_reps', 'back', 'other', 'gym_keeper_apk', '14011305-Muscle-up-(on-vertical-bar)_Back_180.gif', 223),
  ('global', 'Barbell Lateral Lunge', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '14101305-Barbell-Lateral-Lunge_Hips_180.gif', 224),
  ('global', 'Barbell Palms Up Wrist Curl Over A Bench', 'weight_reps', 'arms', 'barbell', 'gym_keeper_apk', '14121305-Barbell-Palms-Up-Wrist-Curl-Over-A-Bench_Forearms_180.gif', 225),
  ('global', 'Reverse Hyper on Flat Bench', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '14231305-Reverse-Hyper-on-Flat-Bench_Hips_180.gif', 226),
  ('global', 'Wide Grip Pull Up', 'weight_reps', 'back', 'bodyweight', 'gym_keeper_apk', '14291305-Wide-Grip-Pull-Up_Back_180.gif', 227),
  ('global', 'Lever Seated Dip', 'weight_reps', 'arms', 'machine', 'gym_keeper_apk', '14511305-Lever-Seated-Dip_Upper-Arms_180.gif', 228),
  ('global', 'Lever Seated Shoulder Press', 'weight_reps', 'shoulders', 'machine', 'gym_keeper_apk', '14541305-Lever-Seated-Shoulder-Press_Shoulders_180.gif', 229),
  ('global', 'Lever Chest Press (VERSION 2)', 'weight_reps', 'chest', 'machine', 'gym_keeper_apk', '14551305-Lever-Chest-Press-(VERSION-2)_Chest_180.gif', 230),
  ('global', 'Dumbbell Romanian Deadlift', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '14591305-Dumbbell-Romanian-Deadlift_Hips_180.gif', 231),
  ('global', 'Bent Leg Kickback (kneeling)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '14741305-Bent-Leg-Kickback-(kneeling)_Hips_180.gif', 232),
  ('global', 'Bent Leg Side Kick (kneeling)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '14751305-Bent-Leg-Side-Kick-(kneeling)_Hips_180.gif', 233),
  ('global', 'Barbell Power Snatch', 'weight_reps', 'other', 'barbell', 'gym_keeper_apk', '15301305-Barbell-Power-Snatch_Weightlifts_180.gif', 234),
  ('global', 'Barbell Stiff Legged Deadlift', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '15431305-Barbell-Stiff-Legged-Deadlift_Hips_180.gif', 235),
  ('global', 'Cable Standing Leg Curl', 'weight_reps', 'legs', 'cable', 'gym_keeper_apk', '15471305-Cable-Standing-Leg-Curl_Thighs_180.gif', 236),
  ('global', 'Dumbbell Squat', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '15551305-Dumbbell-Squat_Thighs_180.gif', 237),
  ('global', 'Bodyweight Rear Lunge', 'weight_reps', 'legs', 'bodyweight', 'gym_keeper_apk', '15811305-Bodyweight-Rear-Lunge_Thighs-FIX_180.gif', 238),
  ('global', 'Smith Front Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '15951305-Smith-Front-Squat_Thighs_180.gif', 239),
  ('global', 'Smith Stiff Legged Deadlift', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '15971305-Smith-Stiff-Legged-Deadlift_Hips_180.gif', 240),
  ('global', 'Cable Biceps Curl (SZ bar)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '16071305-Cable-Biceps-Curl-(SZ-bar)_Upper-arms_180.gif', 241),
  ('global', 'Lever Preacher Curl (version 2)', 'weight_reps', 'arms', 'machine', 'gym_keeper_apk', '16141305-Lever-Preacher-Curl-(version-2)_Upper-Arms_180.gif', 242),
  ('global', 'Cable Concentration Curl', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '16311305-Cable-Concentration-Curl_Upper-Arms_180.gif', 244),
  ('global', 'Cable One Arm Preacher Curl', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '16331305-Cable-One-Arm-Preacher-Curl_Upper-Arms_180.gif', 245),
  ('global', 'Dumbbell Cross Body Hammer Curl (Version 2)', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '16571305-Dumbbell-Cross-Body-Hammer-Curl-(Version-2)_Upper-Arms_180.gif', 246),
  ('global', 'Dumbbell Close Grip Press', 'weight_reps', 'arms', 'dumbbell_pair', 'gym_keeper_apk', '17311305-Dumbbell-Close-Grip-Press_Upper-Arms_180.gif', 247),
  ('global', 'Dumbbell Single Leg Deadlift', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '17571305-Dumbbell-Single-Leg-Deadlift_Hips_180.gif', 248),
  ('global', 'Single Leg Squat (pistol) male', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '17591305-Single-Leg-Squat-(pistol)-male_Thighs_180.gif', 249),
  ('global', 'Hanging Oblique Knee Raise', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '17611305-Hanging-Oblique-Knee-Raise_Waist_180.gif', 250),
  ('global', 'Decline Bent Leg Reverse Crunch', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '18451305-Decline-Bent-Leg-Reverse-Crunch_Waist_180.gif', 251);
