PRAGMA foreign_keys = ON;

-- Generated from the supplied Gym Keeper APK classes2.dex.
-- #34 owns copying the referenced media bytes into R2.
INSERT OR IGNORE INTO exercise_definition (
  scope, name, tracking_type, category_code, equipment_code, reference_source, reference_key, reference_order
) VALUES

  ('global', 'Lever Total Abdominal Crunch', 'time_distance', 'core', 'machine', 'gym_keeper_apk', '18571305-Lever-Total-Abdominal-Crunch_Waist_180.gif', 252),
  ('global', 'Cable Kneeling Triceps Extension (VERSION 2)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '18591305-Cable-Kneeling-Triceps-Extension-(VERSION-2)_Upper-Arms_180.gif', 253),
  ('global', 'Lever Lateral Pulldown (plate loaded)', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '18701305-Lever-Lateral-Pulldown-(plate-loaded)_Back_180.gif', 254),
  ('global', 'Hip Thrusts', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '20721305-Hip-Thrusts_Hips-FIX_180.gif', 255),
  ('global', 'Farmers walk', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '21331305-Farmers-walk_Cardio_180.gif', 256),
  ('global', 'Dumbbell Cuban Press (version 2)', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '21361305-Dumbbell-Cuban-Press-(version-2)_Shoulders_180.gif', 257),
  ('global', 'Dumbbell Arnold Press', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '21371305-Dumbbell-Arnold-Press_Shoulders_180.gif', 258),
  ('global', 'Dumbbell Standing Around World', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '21431305-Dumbbell-Standing-Around-World_Shoulders_180.gif', 259),
  ('global', 'Elliptical Machine Walk', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '21921305-Elliptical-Machine-Walk_Cardio_180.gif', 260),
  ('global', 'Barbell Good Morning (female)', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '22151305-Barbell-Good-Morning-(female)_Thighs_180.gif', 261),
  ('global', 'Barbell Hip Thrust (female)', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '22161305-Barbell-Hip-Thrust-(female)_Hips_180.gif', 262),
  ('global', 'Walking on Treadmill', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '22591305-Walking-on-Treadmill_Cardio_180.gif', 263),
  ('global', 'Lever Pullover (plate loaded)', 'weight_reps', 'back', 'machine', 'gym_keeper_apk', '22851305-Lever-Pullover-(plate-loaded)_Back_180.gif', 264),
  ('global', 'Lever Hip Extension (VERSION 2)', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '22861305-Lever-Hip-Extension-(VERSION-2)_Hips_180.gif', 265),
  ('global', 'Walking on Stepmill', 'time_distance', 'legs', 'other', 'gym_keeper_apk', '23111305-Walking-on-Stepmill_Thighs_180.gif', 266),
  ('global', 'Split Squats', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '23681305-Split-Squats_Thighs-FIX_180.gif', 267),
  ('global', 'Wall Ball', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '24581305-Wall-Ball_Thighs_180.gif', 268),
  ('global', 'Glute Bridge Two Legs on Floor (female)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '24711305-Glute-Bridge-Two-Legs-on-Floor-(female)_Hips_180.gif', 269),
  ('global', 'Jump Rope (male)', 'time_distance', 'cardio', 'other', 'gym_keeper_apk', '26121305-Jump-Rope-(male)_Cardio_180.gif', 270),
  ('global', 'Pike Push up', 'weight_reps', 'chest', 'bodyweight', 'gym_keeper_apk', '29211305-Pike-Push-up_Chest_180.gif', 271),
  ('global', 'Cable Standing Reverse Grip Curl (Straight bar)', 'weight_reps', 'arms', 'cable', 'gym_keeper_apk', '29541305-Cable-Standing-Reverse-Grip-Curl-(Straight-bar)_Forearms_180.gif', 272),
  ('global', 'Dumbbell Split Squat', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '29601305-Dumbbell-Split-Squat_Thighs_180.gif', 273),
  ('global', 'Captains Chair Straight Leg Raise', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '29631305-Captains-Chair-Straight-Leg-Raise_Waist_180.gif', 274),
  ('global', 'Side Lunge', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '29721305-Side-Lunge_Thighs_180.gif', 275),
  ('global', 'Dumbbell Renegade Row', 'weight_reps', 'other', 'dumbbell_pair', 'gym_keeper_apk', '29801305-Dumbbell-Renegade-Row_180.gif', 276),
  ('global', 'Barbell Pendlay Row', 'weight_reps', 'back', 'barbell', 'gym_keeper_apk', '30171305-Barbell-Pendlay-Row_Back_180.gif', 277),
  ('global', 'Barbell Split Squat', 'weight_reps', 'legs', 'barbell', 'gym_keeper_apk', '30301305-Barbell-Split-Squat_Thighs_180.gif', 278),
  ('global', 'Cable hip abduction (version 2) (male)', 'weight_reps', 'legs', 'cable', 'gym_keeper_apk', '30481305-Cable-hip-abduction-(version-2)-(male)_Hips_180.gif', 279),
  ('global', 'Smith Hip Thrust', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '31101305-Smith-Hip-Thrust_Hips_180.gif', 280),
  ('global', 'Smith Sumo Squat', 'weight_reps', 'legs', 'machine', 'gym_keeper_apk', '31421305-Smith-Sumo-Squat_Hips_180.gif', 281),
  ('global', 'Weighted Frog Pump', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '31821305-Weighted-Frog-Pump_Hips_180.gif', 282),
  ('global', 'Glute Ham Raise', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '31931305-Glute-Ham-Raise_Thighs_180.gif', 283),
  ('global', 'Barbell Thruster', 'weight_reps', 'other', 'barbell', 'gym_keeper_apk', '33051305-Barbell-Thruster_180.gif', 284),
  ('global', 'Dumbbell Glute Bridge', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '33351305-Dumbbell-Glute-Bridge_Hip_180.gif', 285),
  ('global', 'Cable Standing Chest Press', 'weight_reps', 'chest', 'cable', 'gym_keeper_apk', '33591305-Cable-Standing-Chest-Press_Chest_180.gif', 286),
  ('global', 'Superman (male)', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '34361305-Superman-(male)_Waist_180.gif', 287),
  ('global', 'Seated In Out Leg Raise on Floor', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '35091305-Seated-In-Out-Leg-Raise-on-Floor_Waist_180.gif', 288),
  ('global', 'Bulgarian Split Squat', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '35331305-Bulgarian-Split-Squat_Thighs_180.gif', 289),
  ('global', 'Side Lying Hip Adduction (male)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '36671305-Side-Lying-Hip-Adduction-(male)_Hips_180.gif', 290),
  ('global', 'Frogger', 'weight_reps', 'core', 'other', 'gym_keeper_apk', '37031305-Frogger_Waist_180.gif', 291),
  ('global', 'Dumbbell Standing Single Leg Calf Raise', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '37131305-Dumbbell-Standing-Single-Leg-Calf-Raise_Calves_180.gif', 292),
  ('global', 'Barbell Behind The Back Shrug', 'weight_reps', 'back', 'barbell', 'gym_keeper_apk', '37301305-Barbell-Behind-The-Back-Shrug_Back_180.gif', 293),
  ('global', 'Crunch (arms straight) (male)', 'time_distance', 'core', 'bodyweight', 'gym_keeper_apk', '38211305-Crunch-(arms-straight)-(male)_waist_180.gif', 294),
  ('global', 'Cable Bent Over Row', 'weight_reps', 'back', 'cable', 'gym_keeper_apk', '38591305-Cable-Bent-Over-Row_Back_180.gif', 295),
  ('global', 'Jump on Fit Box (male)', 'weight_reps', 'other', 'other', 'gym_keeper_apk', '38921305-Jump-on-Fit-Box-(male)_Plyometrics_180.gif', 296),
  ('global', 'Dumbbell Incline Around the World', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '39671305-Dumbbell-Incline-Around-the-World_Shoulders_180.gif', 297),
  ('global', 'Dumbbell Flat Around the World', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '39681305-Dumbbell-Flat-Around-the-World_Shoulders_180.gif', 298),
  ('global', 'Landmine Rear Lunge (VERSION 2)', 'weight_reps', 'legs', 'other', 'gym_keeper_apk', '40401305-Landmine-Rear-Lunge-(VERSION-2)_Thighs_180.gif', 299),
  ('global', 'Dumbbell Seated Bent Over Rear Delt Row', 'weight_reps', 'shoulders', 'dumbbell_pair', 'gym_keeper_apk', '42351305-Dumbbell-Seated-Bent-Over-Rear-Delt-Row_Shoulders_180.gif', 300),
  ('global', 'Dumbbell Decline Lying Leg Curl', 'weight_reps', 'legs', 'dumbbell_pair', 'gym_keeper_apk', '47331305-Dumbbell-Decline-Lying-Leg-Curl_Thighs_180.gif', 301);
