PRAGMA foreign_keys = ON;

-- Exact Russian exercise names extracted from the supplied Gym Keeper APK.
-- The APK seed method pairs each Russian name directly with its GIF reference.
-- Keep reference_key unchanged so #34 media mapping remains deterministic.

UPDATE exercise_definition SET name = 'Жим лежа · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00251305-Barbell-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02891305-Dumbbell-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01511305-Cable-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07481305-Smith-Bench-Press_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (наклон) · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00471305-Barbell-Incline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (наклон) · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03141305-Dumbbell-Incline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (наклон) · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01691305-Cable-Incline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (наклон) · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07571305-Smith-Incline-Bench-Press_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (обратный наклон) · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00331305-Barbell-Decline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (обратный наклон) · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03011305-Dumbbell-Decline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (обратный наклон) · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '12611305-Cable-Decline-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа (обратный наклон) · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07531305-Smith-Decline-Bench-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим от груди сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '14551305-Lever-Chest-Press-(VERSION-2)_Chest_180.gif';
UPDATE exercise_definition SET name = 'Жим от груди стоя · блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '33591305-Cable-Standing-Chest-Press_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03081305-Dumbbell-Fly_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа (наклон) · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03191305-Dumbbell-Incline-Fly_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа (обратный наклон) · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03021305-Dumbbell-Decline-Fly_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук стоя · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '12691305-Cable-Standing-Up-Straight-Crossovers_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение согнутых рук сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '10301305-Lever-Pec-Deck-Fly_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05961305-Lever-Seated-Fly_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01851305-Cable-Lying-Fly_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа (наклон) · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01711305-Cable-Incline-Fly_Chest_180.gif';
UPDATE exercise_definition SET name = 'Сведение рук лежа (обратный наклон) · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01581305-Cable-Decline-Fly_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Пуловер · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '12551305-Barbell-Decline-Pullover_Chest_180.gif';
UPDATE exercise_definition SET name = 'Пуловер · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04331305-Dumbbell-Straight-Arm-Pullover_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Пуловер · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01841305-Cable-Lying-Extension-Pullover-(with-rope-attachment)_180.gif';
UPDATE exercise_definition SET name = 'Пуловер · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '22851305-Lever-Pullover-(plate-loaded)_Back_180.gif';
UPDATE exercise_definition SET name = 'Отжимания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06621305-Push-up-m_Chest-FIX_180.gif';
UPDATE exercise_definition SET name = 'Отжимания в наклоне' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04931305-Incline-Push-up_Chest_180.gif';
UPDATE exercise_definition SET name = 'Отжимания с ногами на возвышении' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02791305-Decline-Push-Up-m_chest_180.gif';
UPDATE exercise_definition SET name = 'Брусья на грудь' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '08141305-Triceps-Dip_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Вокруг света лежа · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '39681305-Dumbbell-Flat-Around-the-World_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00311305-Barbell-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02941305-Dumbbell-Biceps-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16071305-Cable-Biceps-Curl-(SZ-bar)_Upper-arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16141305-Lever-Preacher-Curl-(version-2)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук на наклонной скамье · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03151305-Dumbbell-Incline-Biceps-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Перекрестные сгибания рук · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16571305-Dumbbell-Cross-Body-Hammer-Curl-(Version-2)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук с супинацией · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02851305-Dumbbell-Alternate-Biceps-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибания Зоттмана · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04391305-Dumbbell-Zottman-Curl_Upper-Arms-FIX_180.gif';
UPDATE exercise_definition SET name = 'Паучьи сгибания · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16281305-EZ-Barbell-Spider-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Паучьи сгибания · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03741305-Dumbbell-Prone-Incline-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук молотковым хватом · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03131305-Dumbbell-Hammer-Curl_Forearm_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук молотковым хватом · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01651305-Cable-Hammer-Curl-(with-rope-attachment)-(male)_Forearms-FIX_180.gif';
UPDATE exercise_definition SET name = 'Концентрированные сгибания рук · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00891305-Barbell-Seated-Close-grip-Concentration-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Концентрированные сгибания рук · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02971305-Dumbbell-Concentration-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Концентрированные сгибания рук · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16311305-Cable-Concentration-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Тяга верхнего блока обратным хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '51231305-Cable-Reverse-Grip-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания обратным хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13261305-Chin-Up_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания обратным широким хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '81891305-Wide-Chin-Up-(male)_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания обратным узким хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13271305-Close-Grip-Chin-Up_Back_180.gif';
UPDATE exercise_definition SET name = 'Сгибания рук на скамье Скотта · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04541305-EZ-Barbell-Spider-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибания рук на скамье Скотта · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04021305-Dumbbell-Seated-Preacher-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук на скамье Скотта · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '16331305-Cable-One-Arm-Preacher-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание одной руки на скамье Скотта · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03721305-Dumbbell-Preacher-Curl_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук на скамье Скотта молотковым хватом · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03701305-Dumbbell-Peacher-Hammer-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа узким хватом · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00301305-Barbell-Close-Grip-Bench-Press_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа узким хватом · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '17311305-Dumbbell-Close-Grip-Press_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Жим лежа узким хватом · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07511305-Smith-Close-Grip-Bench-Press_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук лежа · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00611305-Barbell-Lying-Triceps-Extension_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук лежа · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03511305-Dumbbell-Lying-Triceps-Extension_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук лежа · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '52431305-Cable-Lying-Triceps-Extension-(Low)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук сидя · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00921305-Barbell-Seated-Overhead-Triceps-Extension_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук сидя · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03891305-Dumbbell-Seated-Bench-Extension_Upper-Arms-FIX_180.gif';
UPDATE exercise_definition SET name = 'Разгибание одной руки из-за головы · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03621305-Dumbbell-One-Arm-Triceps-Extension-(on-bench)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук из-за головы · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01941305-Cable-Overhead-Triceps-Extension-(rope-attachment)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук из-за головы стоя на коленях · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '18591305-Cable-Kneeling-Triceps-Extension-(VERSION-2)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02411305-Cable-Triceps-Pushdown-(V-bar-attachment)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06071305-Lever-Triceps-Extension_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание рук в наклоне · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04201305-Dumbbell-Standing-Kickback_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание руки в наклоне · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02001305-Cable-One-Arm-Kickback_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Обратные отжимания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13991305-Bench-Dip-(knees-bent)_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Алмазные отжимания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02831305-Diamond-Push-up_Upper-Arms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание кистей · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01081305-Barbell-Seated-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание кистей · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03961305-Dumbbell-Seated-Palms-Up-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание кистей · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02101305-Cable-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание кистей за спиной · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00111305-Barbell-Standing-Back-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание кистей · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00951305-Barbell-Seated-Reverse-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание кистей · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03871305-Dumbbell-Seated-Palms-Down-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Разгибание кистей · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02111305-Cable-Reverse-Wrist-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук обратным хватом · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00791305-Barbell-Reverse-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук обратным хватом · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04051305-Dumbbell-Standing-Reverse-Curl_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Сгибание рук обратным хватом · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02061305-Cable-Reverse-Curl-(SZ-bar)_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Вращение кистей · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '41011305-Dumbbell-Seated-Pronation_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Вращение кистей наружу · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '12331305-Dumbbell-Seated-Pronation-on-Floor_Forearms_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06521305-Pull-up_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания широким хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06781305-Wide-Grip-Pull-Up_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания узким хватом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06511305-Close-Grip-Pull-Up_Back_180.gif';
UPDATE exercise_definition SET name = 'Вертикальная тяга · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01971305-Cable-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Вертикальная тяга узким хватом · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01901305-Cable-Close-Grip-Front-Lat-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Вертикальная тяга за голову · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01961305-Cable-Rear-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Вертикальная тяга · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '23301305-Lever-Front-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга в наклоне · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00271305-Barbell-Bent-Over-Row_Back-FIX_180.gif';
UPDATE exercise_definition SET name = 'Тяга в наклоне · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02931305-Dumbbell-Bent-over-Row_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга одной рукой · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02921305-Dumbbell-Bent-over-Row-with-Chest-Support_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга Т-грифа' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00551305-Barbell-Rear-Delt-Raise_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга Т-грифа с упором' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '21441305-Lever-T-bar-Row_Back_180.gif';
UPDATE exercise_definition SET name = 'Горизонтальная рычажная тяга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13401305-Lever-Seated-Row_Back_180.gif';
UPDATE exercise_definition SET name = 'Горизонтальная тяга сидя · блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02391305-Cable-Seated-Row_Back_180.gif';
UPDATE exercise_definition SET name = 'Горизонтальная тяга стоя · блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '10171305-Cable-Standing-Row-(V-bar)_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга верхнего блока прямыми руками' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02381305-Cable-Straight-Arm-Pulldown_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга каната к лицу · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02451305-Cable-Rear-Delt-Row-(with-rope)_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Шраги · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00951305-Barbell-Shrug_Back_180.gif';
UPDATE exercise_definition SET name = 'Шраги · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04061305-Dumbbell-Shrug_Back_180.gif';
UPDATE exercise_definition SET name = 'Шраги · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07631305-Smith-Shrug_Back_180.gif';
UPDATE exercise_definition SET name = 'Гиперэкстензия' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04891305-Hyperextension_Hips-FIX_180.gif';
UPDATE exercise_definition SET name = 'Гиперэкстензия обратная' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13161305-Reverse-Hyperextension-on-Bench_Hips_180.gif';
UPDATE exercise_definition SET name = 'Доброе утро · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00441305-Barbell-Good-Morning_Hips_180.gif';
UPDATE exercise_definition SET name = 'Птица-собака' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '12411305-Bird-Dog-male_Back_180.gif';
UPDATE exercise_definition SET name = 'Приседания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00431305-Barbell-Full-Squat_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Приседания · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00421305-Barbell-Front-Squat_Hips-FIX_180.gif';
UPDATE exercise_definition SET name = 'Приседания · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03221305-Dumbbell-Squat_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Приседания · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07581305-Smith-Full-Squat_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Гакк-приседания · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00461305-Barbell-Hack-Squat_Hips_180.gif';
UPDATE exercise_definition SET name = 'Гакк-приседания · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07611305-Smith-Hack-Squat_Hips_180.gif';
UPDATE exercise_definition SET name = 'Гакк-приседания · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05851305-Sled-Hack-Squat_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Жим ногами · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07391305-Sled-45-Leg-Press_Hips_180.gif';
UPDATE exercise_definition SET name = 'Разгибание ног · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05851305-Lever-Leg-Extension_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Сгибание ног · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05861305-Lever-Seated-Leg-Curl_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Сгибание ног лежа · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05861305-Lever-Lying-Leg-Curl_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Сгибание ног лежа · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03451305-Dumbbell-Lying-Leg-Curl_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Сгибание ноги стоя · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02051305-Cable-Standing-Leg-Curl_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Румынская тяга · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00851305-Barbell-Romanian-Deadlift_Hips_180.gif';
UPDATE exercise_definition SET name = 'Румынская тяга · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03851305-Dumbbell-Romanian-Deadlift_Hips_180.gif';
UPDATE exercise_definition SET name = 'Становая тяга · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00321305-Barbell-Deadlift_Hips-FIX_180.gif';
UPDATE exercise_definition SET name = 'Становая тяга сумо · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00881305-Barbell-Sumo-Deadlift_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Ягодичный мост · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '14021305-Barbell-Hip-Thrust_Hips_180.gif';
UPDATE exercise_definition SET name = 'Ягодичный мост · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '31561305-Lever-Hip-Thrust_Hips_180.gif';
UPDATE exercise_definition SET name = 'Болгарские приседания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04101305-Bulgarian-Split-Squat_Hips_180.gif';
UPDATE exercise_definition SET name = 'Болгарские приседания · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00321305-Barbell-Bulgarian-Split-Squat_Hips_180.gif';
UPDATE exercise_definition SET name = 'Болгарские приседания · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02901305-Dumbbell-Bulgarian-Split-Squat_Hips_180.gif';
UPDATE exercise_definition SET name = 'Выпады · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00541305-Barbell-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Выпады · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03361305-Dumbbell-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Обратные выпады · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00651305-Barbell-Rear-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Обратные выпады · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03811305-Dumbbell-Rear-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Боковые выпады · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00501305-Barbell-Lateral-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Боковые выпады · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03311305-Dumbbell-Lateral-Lunge_Hips_180.gif';
UPDATE exercise_definition SET name = 'Вышагивания на платформу · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01151305-Barbell-Step-up_Hips_180.gif';
UPDATE exercise_definition SET name = 'Вышагивания на платформу · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04121305-Dumbbell-Step-up_Hips_180.gif';
UPDATE exercise_definition SET name = 'Сведение ног сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05981305-Lever-Seated-Hip-Adduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Разведение ног сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05971305-Lever-Seated-Hip-Abduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Приведение ноги вперед · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01771305-Cable-Hip-Adduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Приведение ноги вперед · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '30191305-Lever-Hip-Adduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Разведение ног стоя · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01761305-Cable-Hip-Abduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Махи ногой назад · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01781305-Cable-Standing-Hip-Extension_Hips_180.gif';
UPDATE exercise_definition SET name = 'Махи ногой назад · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '30181305-Lever-Hip-Extension_Hips_180.gif';
UPDATE exercise_definition SET name = 'Махи ногой вперед · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01791305-Cable-Standing-Hip-Flexion_Hips_180.gif';
UPDATE exercise_definition SET name = 'Разведение ноги в сторону · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01801305-Cable-Standing-Hip-Abduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Разведение ноги в сторону · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '30171305-Lever-Hip-Abduction_Hips_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки стоя · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01111305-Barbell-Standing-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки стоя · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04111305-Dumbbell-Standing-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носок одной ноги стоя' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13711305-Single-Leg-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носок одной ноги стоя · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03841305-Dumbbell-Single-Leg-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки сидя · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00801305-Barbell-Seated-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки сидя · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03861305-Dumbbell-Seated-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05941305-Lever-Seated-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Жим носками · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07391305-Sled-45-Calf-Press_Calves_180.gif';
UPDATE exercise_definition SET name = 'Подъем на носки стоя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06051305-Lever-Standing-Calf-Raise_Calves_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00511305-Barbell-Standing-Military-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03381305-Dumbbell-Standing-Overhead-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02261305-Cable-Standing-Shoulder-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05841305-Lever-Shoulder-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07591305-Smith-Standing-Shoulder-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой сидя · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00881305-Barbell-Seated-Shoulder-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим над головой сидя · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03971305-Dumbbell-Seated-Shoulder-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим Арнольда · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02881305-Dumbbell-Arnold-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Жим из-за головы · тренажер Смита' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07561305-Smith-Behind-Neck-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем перед собой · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00411305-Barbell-Front-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем перед собой · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03121305-Dumbbell-Front-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем перед собой · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01681305-Cable-Front-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъём рук в стороны · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03341305-Dumbbell-Lateral-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъём рук в стороны · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01751305-Cable-Lateral-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъём рук в стороны · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05941305-Lever-Lateral-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем руки в сторону · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01731305-Cable-One-Arm-Lateral-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Разведение рук в наклоне · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03831305-Dumbbell-Reverse-Fly_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Разведение рук в наклоне · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02021305-Cable-Rear-Delt-Fly_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Разведение рук · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06021305-Lever-Reverse-Fly_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Разведение рук · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02461305-Cable-Rear-Delt-Fly-(with-rope)_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Тяга к подбородку · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01181305-Barbell-Upright-Row_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Тяга к подбородку · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04171305-Dumbbell-Upright-Row_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Тяга к подбородку · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02481305-Cable-Upright-Row_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Вокруг света стоя · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '39201305-Dumbbell-Around-the-World_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Вокруг света в наклоне · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '39711305-Dumbbell-Bent-over-Reverse-Fly_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Кубинский жим · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03951305-Dumbbell-Cuban-Press_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Разведения Y · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '35411305-Dumbbell-Y-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Боковой подъем на наклонной скамье · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '35451305-Dumbbell-Lying-One-Arm-Lateral-Raise_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Скручивания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02701305-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Скручивания с поднятыми ногами' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02621305-Air-Bike_Waist_180.gif';
UPDATE exercise_definition SET name = 'Обратные скручивания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '08721305-Reverse-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Скручивания на фитболе' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13431305-Stability-Ball-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Скручивания на верхнем блоке' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02121305-Cable-Kneeling-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Скручивания с поворотом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '08711305-Twisting-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подъем туловища' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '00011305-3-4-Sit-up_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подъем туловища на наклонной скамье' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05001305-Incline-Sit-up_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подъем туловища с поворотом' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '11901305-Incline-Twisting-Sit-up-(version-2)_Waist-FIX_180.gif';
UPDATE exercise_definition SET name = 'Подъем ног лежа' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05201305-Lying-Leg-Raise_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подъем ног в висе' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04721305-Hanging-Straight-Leg-Raise_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подъем коленей в висе' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04731305-Hanging-Knee-Raise_Waist_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания коленей к груди' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '26121305-Seated-In-Out_Waist_180.gif';
UPDATE exercise_definition SET name = 'Планка' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04631305-Front-Plank_Waist_180.gif';
UPDATE exercise_definition SET name = 'Боковая планка' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07111305-Side-Plank_Waist_180.gif';
UPDATE exercise_definition SET name = 'Боковые скручивания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '10211305-Side-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Косые скручивания' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05221305-Oblique-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Русский твист' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06871305-Russian-Twist_Waist_180.gif';
UPDATE exercise_definition SET name = 'Русский твист · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06871305-Russian-Twist-(with-dumbbell)_Waist_180.gif';
UPDATE exercise_definition SET name = 'Дровосек · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02591305-Cable-Wood-Chop_Waist_180.gif';
UPDATE exercise_definition SET name = 'Дровосек · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02581305-Cable-Low-Wood-Chop_Waist_180.gif';
UPDATE exercise_definition SET name = 'Дровосек · гантель' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '34241305-Dumbbell-Wood-Chop_Waist_180.gif';
UPDATE exercise_definition SET name = 'Повороты туловища сидя · тренажер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05831305-Lever-Kneeling-Twist_Waist_180.gif';
UPDATE exercise_definition SET name = 'Наклоны в сторону стоя · верхний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '02231305-Cable-Side-Crunch_Waist_180.gif';
UPDATE exercise_definition SET name = 'Мельница · гиря' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05541305-Kettlebell-Windmill_waist_180.gif';
UPDATE exercise_definition SET name = 'Махи · гиря' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05491305-Kettlebell-Swing_Kettlebell_180.gif';
UPDATE exercise_definition SET name = 'Турецкий подъем · гиря' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05511305-Kettlebell-Turkish-Get-Up-(Squat-style)_Thighs-FIX_180.gif';
UPDATE exercise_definition SET name = 'Прогулка фермера · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '21331305-Farmers-walk_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Железный крест · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '03321305-Dumbbell-Iron-Cross_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Приседания с тягой · нижний блок' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '10031305-Band-squat-row_Back_180.gif';
UPDATE exercise_definition SET name = 'Тяга в упоре лежа · гантели' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '29801305-Dumbbell-Renegade-Row_180.gif';
UPDATE exercise_definition SET name = 'Трастеры · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '33051305-Barbell-Thruster_180.gif';
UPDATE exercise_definition SET name = 'Трастеры · гиря' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05501305-Kettlebell-Thruster_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем на грудь · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06481305-Power-Clean_Weightlifting-FIX_180.gif';
UPDATE exercise_definition SET name = 'Толчок · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '51221305-Barbell-Clean-and-Jerk_Weightlifting_180.gif';
UPDATE exercise_definition SET name = 'Рывок · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '15301305-Barbell-Power-Snatch_Weightlifts_180.gif';
UPDATE exercise_definition SET name = 'Тяга сумо к подбородку · штанга' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '11991305-Sumo-Deadlift-High-Pull_Thighs_Shoulders_180.gif';
UPDATE exercise_definition SET name = 'Подъем силой на перекладине' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '14011305-Muscle-up-(on-vertical-bar)_Back_180.gif';
UPDATE exercise_definition SET name = 'Подтягивания с подъемом колен к подбородку' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04671305-Gorilla-Chin_waist_180.gif';
UPDATE exercise_definition SET name = 'Броски мяча об стену' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '24581305-Wall-Ball_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Броски мяча об пол' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '13541305-Medicine-Ball-Overhead-Slam_Back_180.gif';
UPDATE exercise_definition SET name = 'Беговая дорожка' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '22591305-Walking-on-Treadmill_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Эллипсоид' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '21921305-Elliptical-Machine-Walk_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Велосипед' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '07981305-Stationary-Bike-Walk_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Степпер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '09381305-Lever-stepper_Cardio-copy_180.gif';
UPDATE exercise_definition SET name = 'Лестница-степпер' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '23111305-Walking-on-Stepmill_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Скакалка' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '26121305-Jump-Rope-(male)_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Гребля' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '11611305-Rowing-(with-rowing-machine)_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Волны с канатами' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01281305-Battling-Ropes_180.gif';
UPDATE exercise_definition SET name = 'Берпи' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '11601305-Burpee_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Приседания с выпрыгиванием' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05141305-Jump-Squat_Thighs_180.gif';
UPDATE exercise_definition SET name = 'Скалолаз' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '06301305-Mountain-Climber_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Джампинг Джек' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05161305-Jumping-Jack_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Фроггеры' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '37031305-Frogger_Waist_180.gif';
UPDATE exercise_definition SET name = 'Выпады в прыжке' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '05121305-Jump-Split_Plyometrics_180.gif';
UPDATE exercise_definition SET name = 'Бег с высоким подниманием бедра' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '04771305-High-Knee-Skips_Cardio_180.gif';
UPDATE exercise_definition SET name = 'Захлест голени' WHERE scope = 'global' AND reference_source = 'gym_keeper_apk' AND reference_key = '01461305-Butt-Kicks-(female)_Cardio-FIX_180.gif';
